// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoutingMsg.proto

#ifndef PROTOBUF_INCLUDED_RoutingMsg_2eproto
#define PROTOBUF_INCLUDED_RoutingMsg_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_RoutingMsg_2eproto 

namespace protobuf_RoutingMsg_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_RoutingMsg_2eproto
namespace Planning {
class NextIntersection;
class NextIntersectionDefaultTypeInternal;
extern NextIntersectionDefaultTypeInternal _NextIntersection_default_instance_;
class RoutingPoint;
class RoutingPointDefaultTypeInternal;
extern RoutingPointDefaultTypeInternal _RoutingPoint_default_instance_;
class RoutingPointVec;
class RoutingPointVecDefaultTypeInternal;
extern RoutingPointVecDefaultTypeInternal _RoutingPointVec_default_instance_;
}  // namespace Planning
namespace google {
namespace protobuf {
template<> ::Planning::NextIntersection* Arena::CreateMaybeMessage<::Planning::NextIntersection>(Arena*);
template<> ::Planning::RoutingPoint* Arena::CreateMaybeMessage<::Planning::RoutingPoint>(Arena*);
template<> ::Planning::RoutingPointVec* Arena::CreateMaybeMessage<::Planning::RoutingPointVec>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Planning {

// ===================================================================

class RoutingPoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.RoutingPoint) */ {
 public:
  RoutingPoint();
  virtual ~RoutingPoint();

  RoutingPoint(const RoutingPoint& from);

  inline RoutingPoint& operator=(const RoutingPoint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoutingPoint(RoutingPoint&& from) noexcept
    : RoutingPoint() {
    *this = ::std::move(from);
  }

  inline RoutingPoint& operator=(RoutingPoint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingPoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoutingPoint* internal_default_instance() {
    return reinterpret_cast<const RoutingPoint*>(
               &_RoutingPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RoutingPoint* other);
  friend void swap(RoutingPoint& a, RoutingPoint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoutingPoint* New() const final {
    return CreateMaybeMessage<RoutingPoint>(NULL);
  }

  RoutingPoint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoutingPoint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoutingPoint& from);
  void MergeFrom(const RoutingPoint& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoutingPoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double Longtitude = 1;
  void clear_longtitude();
  static const int kLongtitudeFieldNumber = 1;
  double longtitude() const;
  void set_longtitude(double value);

  // double Latitude = 2;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 2;
  double latitude() const;
  void set_latitude(double value);

  // double Height = 3;
  void clear_height();
  static const int kHeightFieldNumber = 3;
  double height() const;
  void set_height(double value);

  // @@protoc_insertion_point(class_scope:Planning.RoutingPoint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double longtitude_;
  double latitude_;
  double height_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_RoutingMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NextIntersection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.NextIntersection) */ {
 public:
  NextIntersection();
  virtual ~NextIntersection();

  NextIntersection(const NextIntersection& from);

  inline NextIntersection& operator=(const NextIntersection& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NextIntersection(NextIntersection&& from) noexcept
    : NextIntersection() {
    *this = ::std::move(from);
  }

  inline NextIntersection& operator=(NextIntersection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NextIntersection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NextIntersection* internal_default_instance() {
    return reinterpret_cast<const NextIntersection*>(
               &_NextIntersection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(NextIntersection* other);
  friend void swap(NextIntersection& a, NextIntersection& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NextIntersection* New() const final {
    return CreateMaybeMessage<NextIntersection>(NULL);
  }

  NextIntersection* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NextIntersection>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NextIntersection& from);
  void MergeFrom(const NextIntersection& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NextIntersection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string intersectionId = 10;
  void clear_intersectionid();
  static const int kIntersectionIdFieldNumber = 10;
  const ::std::string& intersectionid() const;
  void set_intersectionid(const ::std::string& value);
  #if LANG_CXX11
  void set_intersectionid(::std::string&& value);
  #endif
  void set_intersectionid(const char* value);
  void set_intersectionid(const char* value, size_t size);
  ::std::string* mutable_intersectionid();
  ::std::string* release_intersectionid();
  void set_allocated_intersectionid(::std::string* intersectionid);

  // string shape = 12;
  void clear_shape();
  static const int kShapeFieldNumber = 12;
  const ::std::string& shape() const;
  void set_shape(const ::std::string& value);
  #if LANG_CXX11
  void set_shape(::std::string&& value);
  #endif
  void set_shape(const char* value);
  void set_shape(const char* value, size_t size);
  ::std::string* mutable_shape();
  ::std::string* release_shape();
  void set_allocated_shape(::std::string* shape);

  // int32 currentRoadID = 1;
  void clear_currentroadid();
  static const int kCurrentRoadIDFieldNumber = 1;
  ::google::protobuf::int32 currentroadid() const;
  void set_currentroadid(::google::protobuf::int32 value);

  // int32 currentLaneID = 2;
  void clear_currentlaneid();
  static const int kCurrentLaneIDFieldNumber = 2;
  ::google::protobuf::int32 currentlaneid() const;
  void set_currentlaneid(::google::protobuf::int32 value);

  // int32 currentPointID = 3;
  void clear_currentpointid();
  static const int kCurrentPointIDFieldNumber = 3;
  ::google::protobuf::int32 currentpointid() const;
  void set_currentpointid(::google::protobuf::int32 value);

  // int32 nextRoadID = 4;
  void clear_nextroadid();
  static const int kNextRoadIDFieldNumber = 4;
  ::google::protobuf::int32 nextroadid() const;
  void set_nextroadid(::google::protobuf::int32 value);

  // double trafficLightGaussX = 6;
  void clear_trafficlightgaussx();
  static const int kTrafficLightGaussXFieldNumber = 6;
  double trafficlightgaussx() const;
  void set_trafficlightgaussx(double value);

  // double trafficLightGaussY = 7;
  void clear_trafficlightgaussy();
  static const int kTrafficLightGaussYFieldNumber = 7;
  double trafficlightgaussy() const;
  void set_trafficlightgaussy(double value);

  // int32 nextLaneID = 5;
  void clear_nextlaneid();
  static const int kNextLaneIDFieldNumber = 5;
  ::google::protobuf::int32 nextlaneid() const;
  void set_nextlaneid(::google::protobuf::int32 value);

  // int32 directionOfTravel = 9;
  void clear_directionoftravel();
  static const int kDirectionOfTravelFieldNumber = 9;
  ::google::protobuf::int32 directionoftravel() const;
  void set_directionoftravel(::google::protobuf::int32 value);

  // double trafficLightHeight = 8;
  void clear_trafficlightheight();
  static const int kTrafficLightHeightFieldNumber = 8;
  double trafficlightheight() const;
  void set_trafficlightheight(double value);

  // int64 phaseID = 11;
  void clear_phaseid();
  static const int kPhaseIDFieldNumber = 11;
  ::google::protobuf::int64 phaseid() const;
  void set_phaseid(::google::protobuf::int64 value);

  // int32 lightsum = 13;
  void clear_lightsum();
  static const int kLightsumFieldNumber = 13;
  ::google::protobuf::int32 lightsum() const;
  void set_lightsum(::google::protobuf::int32 value);

  // int32 lightIdx = 14;
  void clear_lightidx();
  static const int kLightIdxFieldNumber = 14;
  ::google::protobuf::int32 lightidx() const;
  void set_lightidx(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Planning.NextIntersection)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr intersectionid_;
  ::google::protobuf::internal::ArenaStringPtr shape_;
  ::google::protobuf::int32 currentroadid_;
  ::google::protobuf::int32 currentlaneid_;
  ::google::protobuf::int32 currentpointid_;
  ::google::protobuf::int32 nextroadid_;
  double trafficlightgaussx_;
  double trafficlightgaussy_;
  ::google::protobuf::int32 nextlaneid_;
  ::google::protobuf::int32 directionoftravel_;
  double trafficlightheight_;
  ::google::protobuf::int64 phaseid_;
  ::google::protobuf::int32 lightsum_;
  ::google::protobuf::int32 lightidx_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_RoutingMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoutingPointVec : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.RoutingPointVec) */ {
 public:
  RoutingPointVec();
  virtual ~RoutingPointVec();

  RoutingPointVec(const RoutingPointVec& from);

  inline RoutingPointVec& operator=(const RoutingPointVec& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoutingPointVec(RoutingPointVec&& from) noexcept
    : RoutingPointVec() {
    *this = ::std::move(from);
  }

  inline RoutingPointVec& operator=(RoutingPointVec&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingPointVec& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoutingPointVec* internal_default_instance() {
    return reinterpret_cast<const RoutingPointVec*>(
               &_RoutingPointVec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RoutingPointVec* other);
  friend void swap(RoutingPointVec& a, RoutingPointVec& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoutingPointVec* New() const final {
    return CreateMaybeMessage<RoutingPointVec>(NULL);
  }

  RoutingPointVec* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoutingPointVec>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoutingPointVec& from);
  void MergeFrom(const RoutingPointVec& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoutingPointVec* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Planning.RoutingPoint RoutingPoints = 1;
  int routingpoints_size() const;
  void clear_routingpoints();
  static const int kRoutingPointsFieldNumber = 1;
  ::Planning::RoutingPoint* mutable_routingpoints(int index);
  ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint >*
      mutable_routingpoints();
  const ::Planning::RoutingPoint& routingpoints(int index) const;
  ::Planning::RoutingPoint* add_routingpoints();
  const ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint >&
      routingpoints() const;

  // .Planning.NextIntersection nextIntersection = 2;
  bool has_nextintersection() const;
  void clear_nextintersection();
  static const int kNextIntersectionFieldNumber = 2;
  private:
  const ::Planning::NextIntersection& _internal_nextintersection() const;
  public:
  const ::Planning::NextIntersection& nextintersection() const;
  ::Planning::NextIntersection* release_nextintersection();
  ::Planning::NextIntersection* mutable_nextintersection();
  void set_allocated_nextintersection(::Planning::NextIntersection* nextintersection);

  // @@protoc_insertion_point(class_scope:Planning.RoutingPointVec)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint > routingpoints_;
  ::Planning::NextIntersection* nextintersection_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_RoutingMsg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoutingPoint

// double Longtitude = 1;
inline void RoutingPoint::clear_longtitude() {
  longtitude_ = 0;
}
inline double RoutingPoint::longtitude() const {
  // @@protoc_insertion_point(field_get:Planning.RoutingPoint.Longtitude)
  return longtitude_;
}
inline void RoutingPoint::set_longtitude(double value) {
  
  longtitude_ = value;
  // @@protoc_insertion_point(field_set:Planning.RoutingPoint.Longtitude)
}

// double Latitude = 2;
inline void RoutingPoint::clear_latitude() {
  latitude_ = 0;
}
inline double RoutingPoint::latitude() const {
  // @@protoc_insertion_point(field_get:Planning.RoutingPoint.Latitude)
  return latitude_;
}
inline void RoutingPoint::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:Planning.RoutingPoint.Latitude)
}

// double Height = 3;
inline void RoutingPoint::clear_height() {
  height_ = 0;
}
inline double RoutingPoint::height() const {
  // @@protoc_insertion_point(field_get:Planning.RoutingPoint.Height)
  return height_;
}
inline void RoutingPoint::set_height(double value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:Planning.RoutingPoint.Height)
}

// -------------------------------------------------------------------

// NextIntersection

// int32 currentRoadID = 1;
inline void NextIntersection::clear_currentroadid() {
  currentroadid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::currentroadid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.currentRoadID)
  return currentroadid_;
}
inline void NextIntersection::set_currentroadid(::google::protobuf::int32 value) {
  
  currentroadid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.currentRoadID)
}

// int32 currentLaneID = 2;
inline void NextIntersection::clear_currentlaneid() {
  currentlaneid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::currentlaneid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.currentLaneID)
  return currentlaneid_;
}
inline void NextIntersection::set_currentlaneid(::google::protobuf::int32 value) {
  
  currentlaneid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.currentLaneID)
}

// int32 currentPointID = 3;
inline void NextIntersection::clear_currentpointid() {
  currentpointid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::currentpointid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.currentPointID)
  return currentpointid_;
}
inline void NextIntersection::set_currentpointid(::google::protobuf::int32 value) {
  
  currentpointid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.currentPointID)
}

// int32 nextRoadID = 4;
inline void NextIntersection::clear_nextroadid() {
  nextroadid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::nextroadid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.nextRoadID)
  return nextroadid_;
}
inline void NextIntersection::set_nextroadid(::google::protobuf::int32 value) {
  
  nextroadid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.nextRoadID)
}

// int32 nextLaneID = 5;
inline void NextIntersection::clear_nextlaneid() {
  nextlaneid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::nextlaneid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.nextLaneID)
  return nextlaneid_;
}
inline void NextIntersection::set_nextlaneid(::google::protobuf::int32 value) {
  
  nextlaneid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.nextLaneID)
}

// double trafficLightGaussX = 6;
inline void NextIntersection::clear_trafficlightgaussx() {
  trafficlightgaussx_ = 0;
}
inline double NextIntersection::trafficlightgaussx() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.trafficLightGaussX)
  return trafficlightgaussx_;
}
inline void NextIntersection::set_trafficlightgaussx(double value) {
  
  trafficlightgaussx_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.trafficLightGaussX)
}

// double trafficLightGaussY = 7;
inline void NextIntersection::clear_trafficlightgaussy() {
  trafficlightgaussy_ = 0;
}
inline double NextIntersection::trafficlightgaussy() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.trafficLightGaussY)
  return trafficlightgaussy_;
}
inline void NextIntersection::set_trafficlightgaussy(double value) {
  
  trafficlightgaussy_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.trafficLightGaussY)
}

// double trafficLightHeight = 8;
inline void NextIntersection::clear_trafficlightheight() {
  trafficlightheight_ = 0;
}
inline double NextIntersection::trafficlightheight() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.trafficLightHeight)
  return trafficlightheight_;
}
inline void NextIntersection::set_trafficlightheight(double value) {
  
  trafficlightheight_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.trafficLightHeight)
}

// int32 directionOfTravel = 9;
inline void NextIntersection::clear_directionoftravel() {
  directionoftravel_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::directionoftravel() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.directionOfTravel)
  return directionoftravel_;
}
inline void NextIntersection::set_directionoftravel(::google::protobuf::int32 value) {
  
  directionoftravel_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.directionOfTravel)
}

// string intersectionId = 10;
inline void NextIntersection::clear_intersectionid() {
  intersectionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NextIntersection::intersectionid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.intersectionId)
  return intersectionid_.GetNoArena();
}
inline void NextIntersection::set_intersectionid(const ::std::string& value) {
  
  intersectionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.intersectionId)
}
#if LANG_CXX11
inline void NextIntersection::set_intersectionid(::std::string&& value) {
  
  intersectionid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Planning.NextIntersection.intersectionId)
}
#endif
inline void NextIntersection::set_intersectionid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  intersectionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Planning.NextIntersection.intersectionId)
}
inline void NextIntersection::set_intersectionid(const char* value, size_t size) {
  
  intersectionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Planning.NextIntersection.intersectionId)
}
inline ::std::string* NextIntersection::mutable_intersectionid() {
  
  // @@protoc_insertion_point(field_mutable:Planning.NextIntersection.intersectionId)
  return intersectionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NextIntersection::release_intersectionid() {
  // @@protoc_insertion_point(field_release:Planning.NextIntersection.intersectionId)
  
  return intersectionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NextIntersection::set_allocated_intersectionid(::std::string* intersectionid) {
  if (intersectionid != NULL) {
    
  } else {
    
  }
  intersectionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), intersectionid);
  // @@protoc_insertion_point(field_set_allocated:Planning.NextIntersection.intersectionId)
}

// int64 phaseID = 11;
inline void NextIntersection::clear_phaseid() {
  phaseid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 NextIntersection::phaseid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.phaseID)
  return phaseid_;
}
inline void NextIntersection::set_phaseid(::google::protobuf::int64 value) {
  
  phaseid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.phaseID)
}

// string shape = 12;
inline void NextIntersection::clear_shape() {
  shape_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NextIntersection::shape() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.shape)
  return shape_.GetNoArena();
}
inline void NextIntersection::set_shape(const ::std::string& value) {
  
  shape_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.shape)
}
#if LANG_CXX11
inline void NextIntersection::set_shape(::std::string&& value) {
  
  shape_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Planning.NextIntersection.shape)
}
#endif
inline void NextIntersection::set_shape(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  shape_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Planning.NextIntersection.shape)
}
inline void NextIntersection::set_shape(const char* value, size_t size) {
  
  shape_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Planning.NextIntersection.shape)
}
inline ::std::string* NextIntersection::mutable_shape() {
  
  // @@protoc_insertion_point(field_mutable:Planning.NextIntersection.shape)
  return shape_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NextIntersection::release_shape() {
  // @@protoc_insertion_point(field_release:Planning.NextIntersection.shape)
  
  return shape_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NextIntersection::set_allocated_shape(::std::string* shape) {
  if (shape != NULL) {
    
  } else {
    
  }
  shape_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shape);
  // @@protoc_insertion_point(field_set_allocated:Planning.NextIntersection.shape)
}

// int32 lightsum = 13;
inline void NextIntersection::clear_lightsum() {
  lightsum_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::lightsum() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.lightsum)
  return lightsum_;
}
inline void NextIntersection::set_lightsum(::google::protobuf::int32 value) {
  
  lightsum_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.lightsum)
}

// int32 lightIdx = 14;
inline void NextIntersection::clear_lightidx() {
  lightidx_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::lightidx() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.lightIdx)
  return lightidx_;
}
inline void NextIntersection::set_lightidx(::google::protobuf::int32 value) {
  
  lightidx_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.lightIdx)
}

// -------------------------------------------------------------------

// RoutingPointVec

// repeated .Planning.RoutingPoint RoutingPoints = 1;
inline int RoutingPointVec::routingpoints_size() const {
  return routingpoints_.size();
}
inline void RoutingPointVec::clear_routingpoints() {
  routingpoints_.Clear();
}
inline ::Planning::RoutingPoint* RoutingPointVec::mutable_routingpoints(int index) {
  // @@protoc_insertion_point(field_mutable:Planning.RoutingPointVec.RoutingPoints)
  return routingpoints_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint >*
RoutingPointVec::mutable_routingpoints() {
  // @@protoc_insertion_point(field_mutable_list:Planning.RoutingPointVec.RoutingPoints)
  return &routingpoints_;
}
inline const ::Planning::RoutingPoint& RoutingPointVec::routingpoints(int index) const {
  // @@protoc_insertion_point(field_get:Planning.RoutingPointVec.RoutingPoints)
  return routingpoints_.Get(index);
}
inline ::Planning::RoutingPoint* RoutingPointVec::add_routingpoints() {
  // @@protoc_insertion_point(field_add:Planning.RoutingPointVec.RoutingPoints)
  return routingpoints_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint >&
RoutingPointVec::routingpoints() const {
  // @@protoc_insertion_point(field_list:Planning.RoutingPointVec.RoutingPoints)
  return routingpoints_;
}

// .Planning.NextIntersection nextIntersection = 2;
inline bool RoutingPointVec::has_nextintersection() const {
  return this != internal_default_instance() && nextintersection_ != NULL;
}
inline void RoutingPointVec::clear_nextintersection() {
  if (GetArenaNoVirtual() == NULL && nextintersection_ != NULL) {
    delete nextintersection_;
  }
  nextintersection_ = NULL;
}
inline const ::Planning::NextIntersection& RoutingPointVec::_internal_nextintersection() const {
  return *nextintersection_;
}
inline const ::Planning::NextIntersection& RoutingPointVec::nextintersection() const {
  const ::Planning::NextIntersection* p = nextintersection_;
  // @@protoc_insertion_point(field_get:Planning.RoutingPointVec.nextIntersection)
  return p != NULL ? *p : *reinterpret_cast<const ::Planning::NextIntersection*>(
      &::Planning::_NextIntersection_default_instance_);
}
inline ::Planning::NextIntersection* RoutingPointVec::release_nextintersection() {
  // @@protoc_insertion_point(field_release:Planning.RoutingPointVec.nextIntersection)
  
  ::Planning::NextIntersection* temp = nextintersection_;
  nextintersection_ = NULL;
  return temp;
}
inline ::Planning::NextIntersection* RoutingPointVec::mutable_nextintersection() {
  
  if (nextintersection_ == NULL) {
    auto* p = CreateMaybeMessage<::Planning::NextIntersection>(GetArenaNoVirtual());
    nextintersection_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Planning.RoutingPointVec.nextIntersection)
  return nextintersection_;
}
inline void RoutingPointVec::set_allocated_nextintersection(::Planning::NextIntersection* nextintersection) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete nextintersection_;
  }
  if (nextintersection) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      nextintersection = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, nextintersection, submessage_arena);
    }
    
  } else {
    
  }
  nextintersection_ = nextintersection;
  // @@protoc_insertion_point(field_set_allocated:Planning.RoutingPointVec.nextIntersection)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Planning

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_RoutingMsg_2eproto
