// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoutingMsg.proto

#ifndef PROTOBUF_RoutingMsg_2eproto__INCLUDED
#define PROTOBUF_RoutingMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Planning {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_RoutingMsg_2eproto();
void protobuf_AssignDesc_RoutingMsg_2eproto();
void protobuf_ShutdownFile_RoutingMsg_2eproto();

class NextIntersection;
class RoutingPoint;
class RoutingPointVec;

// ===================================================================

class RoutingPoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.RoutingPoint) */ {
 public:
  RoutingPoint();
  virtual ~RoutingPoint();

  RoutingPoint(const RoutingPoint& from);

  inline RoutingPoint& operator=(const RoutingPoint& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingPoint& default_instance();

  void Swap(RoutingPoint* other);

  // implements Message ----------------------------------------------

  inline RoutingPoint* New() const { return New(NULL); }

  RoutingPoint* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RoutingPoint& from);
  void MergeFrom(const RoutingPoint& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RoutingPoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double Longtitude = 1;
  void clear_longtitude();
  static const int kLongtitudeFieldNumber = 1;
  double longtitude() const;
  void set_longtitude(double value);

  // optional double Latitude = 2;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 2;
  double latitude() const;
  void set_latitude(double value);

  // optional double Height = 3;
  void clear_height();
  static const int kHeightFieldNumber = 3;
  double height() const;
  void set_height(double value);

  // @@protoc_insertion_point(class_scope:Planning.RoutingPoint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double longtitude_;
  double latitude_;
  double height_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_RoutingMsg_2eproto();
  friend void protobuf_AssignDesc_RoutingMsg_2eproto();
  friend void protobuf_ShutdownFile_RoutingMsg_2eproto();

  void InitAsDefaultInstance();
  static RoutingPoint* default_instance_;
};
// -------------------------------------------------------------------

class NextIntersection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.NextIntersection) */ {
 public:
  NextIntersection();
  virtual ~NextIntersection();

  NextIntersection(const NextIntersection& from);

  inline NextIntersection& operator=(const NextIntersection& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NextIntersection& default_instance();

  void Swap(NextIntersection* other);

  // implements Message ----------------------------------------------

  inline NextIntersection* New() const { return New(NULL); }

  NextIntersection* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NextIntersection& from);
  void MergeFrom(const NextIntersection& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(NextIntersection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 currentRoadID = 1;
  void clear_currentroadid();
  static const int kCurrentRoadIDFieldNumber = 1;
  ::google::protobuf::int32 currentroadid() const;
  void set_currentroadid(::google::protobuf::int32 value);

  // optional int32 currentLaneID = 2;
  void clear_currentlaneid();
  static const int kCurrentLaneIDFieldNumber = 2;
  ::google::protobuf::int32 currentlaneid() const;
  void set_currentlaneid(::google::protobuf::int32 value);

  // optional int32 currentPointID = 3;
  void clear_currentpointid();
  static const int kCurrentPointIDFieldNumber = 3;
  ::google::protobuf::int32 currentpointid() const;
  void set_currentpointid(::google::protobuf::int32 value);

  // optional int32 nextRoadID = 4;
  void clear_nextroadid();
  static const int kNextRoadIDFieldNumber = 4;
  ::google::protobuf::int32 nextroadid() const;
  void set_nextroadid(::google::protobuf::int32 value);

  // optional int32 nextLaneID = 5;
  void clear_nextlaneid();
  static const int kNextLaneIDFieldNumber = 5;
  ::google::protobuf::int32 nextlaneid() const;
  void set_nextlaneid(::google::protobuf::int32 value);

  // optional double trafficLightGaussX = 6;
  void clear_trafficlightgaussx();
  static const int kTrafficLightGaussXFieldNumber = 6;
  double trafficlightgaussx() const;
  void set_trafficlightgaussx(double value);

  // optional double trafficLightGaussY = 7;
  void clear_trafficlightgaussy();
  static const int kTrafficLightGaussYFieldNumber = 7;
  double trafficlightgaussy() const;
  void set_trafficlightgaussy(double value);

  // optional double trafficLightHeight = 8;
  void clear_trafficlightheight();
  static const int kTrafficLightHeightFieldNumber = 8;
  double trafficlightheight() const;
  void set_trafficlightheight(double value);

  // optional int32 directionOfTravel = 9;
  void clear_directionoftravel();
  static const int kDirectionOfTravelFieldNumber = 9;
  ::google::protobuf::int32 directionoftravel() const;
  void set_directionoftravel(::google::protobuf::int32 value);

  // optional string intersectionId = 10;
  void clear_intersectionid();
  static const int kIntersectionIdFieldNumber = 10;
  const ::std::string& intersectionid() const;
  void set_intersectionid(const ::std::string& value);
  void set_intersectionid(const char* value);
  void set_intersectionid(const char* value, size_t size);
  ::std::string* mutable_intersectionid();
  ::std::string* release_intersectionid();
  void set_allocated_intersectionid(::std::string* intersectionid);

  // optional int64 phaseID = 11;
  void clear_phaseid();
  static const int kPhaseIDFieldNumber = 11;
  ::google::protobuf::int64 phaseid() const;
  void set_phaseid(::google::protobuf::int64 value);

  // optional string shape = 12;
  void clear_shape();
  static const int kShapeFieldNumber = 12;
  const ::std::string& shape() const;
  void set_shape(const ::std::string& value);
  void set_shape(const char* value);
  void set_shape(const char* value, size_t size);
  ::std::string* mutable_shape();
  ::std::string* release_shape();
  void set_allocated_shape(::std::string* shape);

  // optional int32 lightsum = 13;
  void clear_lightsum();
  static const int kLightsumFieldNumber = 13;
  ::google::protobuf::int32 lightsum() const;
  void set_lightsum(::google::protobuf::int32 value);

  // optional int32 lightIdx = 14;
  void clear_lightidx();
  static const int kLightIdxFieldNumber = 14;
  ::google::protobuf::int32 lightidx() const;
  void set_lightidx(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Planning.NextIntersection)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 currentroadid_;
  ::google::protobuf::int32 currentlaneid_;
  ::google::protobuf::int32 currentpointid_;
  ::google::protobuf::int32 nextroadid_;
  double trafficlightgaussx_;
  double trafficlightgaussy_;
  ::google::protobuf::int32 nextlaneid_;
  ::google::protobuf::int32 directionoftravel_;
  double trafficlightheight_;
  ::google::protobuf::internal::ArenaStringPtr intersectionid_;
  ::google::protobuf::int64 phaseid_;
  ::google::protobuf::internal::ArenaStringPtr shape_;
  ::google::protobuf::int32 lightsum_;
  ::google::protobuf::int32 lightidx_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_RoutingMsg_2eproto();
  friend void protobuf_AssignDesc_RoutingMsg_2eproto();
  friend void protobuf_ShutdownFile_RoutingMsg_2eproto();

  void InitAsDefaultInstance();
  static NextIntersection* default_instance_;
};
// -------------------------------------------------------------------

class RoutingPointVec : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.RoutingPointVec) */ {
 public:
  RoutingPointVec();
  virtual ~RoutingPointVec();

  RoutingPointVec(const RoutingPointVec& from);

  inline RoutingPointVec& operator=(const RoutingPointVec& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingPointVec& default_instance();

  void Swap(RoutingPointVec* other);

  // implements Message ----------------------------------------------

  inline RoutingPointVec* New() const { return New(NULL); }

  RoutingPointVec* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RoutingPointVec& from);
  void MergeFrom(const RoutingPointVec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RoutingPointVec* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Planning.RoutingPoint RoutingPoints = 1;
  int routingpoints_size() const;
  void clear_routingpoints();
  static const int kRoutingPointsFieldNumber = 1;
  const ::Planning::RoutingPoint& routingpoints(int index) const;
  ::Planning::RoutingPoint* mutable_routingpoints(int index);
  ::Planning::RoutingPoint* add_routingpoints();
  ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint >*
      mutable_routingpoints();
  const ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint >&
      routingpoints() const;

  // optional .Planning.NextIntersection nextIntersection = 2;
  bool has_nextintersection() const;
  void clear_nextintersection();
  static const int kNextIntersectionFieldNumber = 2;
  const ::Planning::NextIntersection& nextintersection() const;
  ::Planning::NextIntersection* mutable_nextintersection();
  ::Planning::NextIntersection* release_nextintersection();
  void set_allocated_nextintersection(::Planning::NextIntersection* nextintersection);

  // @@protoc_insertion_point(class_scope:Planning.RoutingPointVec)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint > routingpoints_;
  ::Planning::NextIntersection* nextintersection_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_RoutingMsg_2eproto();
  friend void protobuf_AssignDesc_RoutingMsg_2eproto();
  friend void protobuf_ShutdownFile_RoutingMsg_2eproto();

  void InitAsDefaultInstance();
  static RoutingPointVec* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RoutingPoint

// optional double Longtitude = 1;
inline void RoutingPoint::clear_longtitude() {
  longtitude_ = 0;
}
inline double RoutingPoint::longtitude() const {
  // @@protoc_insertion_point(field_get:Planning.RoutingPoint.Longtitude)
  return longtitude_;
}
inline void RoutingPoint::set_longtitude(double value) {
  
  longtitude_ = value;
  // @@protoc_insertion_point(field_set:Planning.RoutingPoint.Longtitude)
}

// optional double Latitude = 2;
inline void RoutingPoint::clear_latitude() {
  latitude_ = 0;
}
inline double RoutingPoint::latitude() const {
  // @@protoc_insertion_point(field_get:Planning.RoutingPoint.Latitude)
  return latitude_;
}
inline void RoutingPoint::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:Planning.RoutingPoint.Latitude)
}

// optional double Height = 3;
inline void RoutingPoint::clear_height() {
  height_ = 0;
}
inline double RoutingPoint::height() const {
  // @@protoc_insertion_point(field_get:Planning.RoutingPoint.Height)
  return height_;
}
inline void RoutingPoint::set_height(double value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:Planning.RoutingPoint.Height)
}

// -------------------------------------------------------------------

// NextIntersection

// optional int32 currentRoadID = 1;
inline void NextIntersection::clear_currentroadid() {
  currentroadid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::currentroadid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.currentRoadID)
  return currentroadid_;
}
inline void NextIntersection::set_currentroadid(::google::protobuf::int32 value) {
  
  currentroadid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.currentRoadID)
}

// optional int32 currentLaneID = 2;
inline void NextIntersection::clear_currentlaneid() {
  currentlaneid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::currentlaneid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.currentLaneID)
  return currentlaneid_;
}
inline void NextIntersection::set_currentlaneid(::google::protobuf::int32 value) {
  
  currentlaneid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.currentLaneID)
}

// optional int32 currentPointID = 3;
inline void NextIntersection::clear_currentpointid() {
  currentpointid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::currentpointid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.currentPointID)
  return currentpointid_;
}
inline void NextIntersection::set_currentpointid(::google::protobuf::int32 value) {
  
  currentpointid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.currentPointID)
}

// optional int32 nextRoadID = 4;
inline void NextIntersection::clear_nextroadid() {
  nextroadid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::nextroadid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.nextRoadID)
  return nextroadid_;
}
inline void NextIntersection::set_nextroadid(::google::protobuf::int32 value) {
  
  nextroadid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.nextRoadID)
}

// optional int32 nextLaneID = 5;
inline void NextIntersection::clear_nextlaneid() {
  nextlaneid_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::nextlaneid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.nextLaneID)
  return nextlaneid_;
}
inline void NextIntersection::set_nextlaneid(::google::protobuf::int32 value) {
  
  nextlaneid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.nextLaneID)
}

// optional double trafficLightGaussX = 6;
inline void NextIntersection::clear_trafficlightgaussx() {
  trafficlightgaussx_ = 0;
}
inline double NextIntersection::trafficlightgaussx() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.trafficLightGaussX)
  return trafficlightgaussx_;
}
inline void NextIntersection::set_trafficlightgaussx(double value) {
  
  trafficlightgaussx_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.trafficLightGaussX)
}

// optional double trafficLightGaussY = 7;
inline void NextIntersection::clear_trafficlightgaussy() {
  trafficlightgaussy_ = 0;
}
inline double NextIntersection::trafficlightgaussy() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.trafficLightGaussY)
  return trafficlightgaussy_;
}
inline void NextIntersection::set_trafficlightgaussy(double value) {
  
  trafficlightgaussy_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.trafficLightGaussY)
}

// optional double trafficLightHeight = 8;
inline void NextIntersection::clear_trafficlightheight() {
  trafficlightheight_ = 0;
}
inline double NextIntersection::trafficlightheight() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.trafficLightHeight)
  return trafficlightheight_;
}
inline void NextIntersection::set_trafficlightheight(double value) {
  
  trafficlightheight_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.trafficLightHeight)
}

// optional int32 directionOfTravel = 9;
inline void NextIntersection::clear_directionoftravel() {
  directionoftravel_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::directionoftravel() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.directionOfTravel)
  return directionoftravel_;
}
inline void NextIntersection::set_directionoftravel(::google::protobuf::int32 value) {
  
  directionoftravel_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.directionOfTravel)
}

// optional string intersectionId = 10;
inline void NextIntersection::clear_intersectionid() {
  intersectionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NextIntersection::intersectionid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.intersectionId)
  return intersectionid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NextIntersection::set_intersectionid(const ::std::string& value) {
  
  intersectionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.intersectionId)
}
inline void NextIntersection::set_intersectionid(const char* value) {
  
  intersectionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Planning.NextIntersection.intersectionId)
}
inline void NextIntersection::set_intersectionid(const char* value, size_t size) {
  
  intersectionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Planning.NextIntersection.intersectionId)
}
inline ::std::string* NextIntersection::mutable_intersectionid() {
  
  // @@protoc_insertion_point(field_mutable:Planning.NextIntersection.intersectionId)
  return intersectionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NextIntersection::release_intersectionid() {
  // @@protoc_insertion_point(field_release:Planning.NextIntersection.intersectionId)
  
  return intersectionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NextIntersection::set_allocated_intersectionid(::std::string* intersectionid) {
  if (intersectionid != NULL) {
    
  } else {
    
  }
  intersectionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), intersectionid);
  // @@protoc_insertion_point(field_set_allocated:Planning.NextIntersection.intersectionId)
}

// optional int64 phaseID = 11;
inline void NextIntersection::clear_phaseid() {
  phaseid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 NextIntersection::phaseid() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.phaseID)
  return phaseid_;
}
inline void NextIntersection::set_phaseid(::google::protobuf::int64 value) {
  
  phaseid_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.phaseID)
}

// optional string shape = 12;
inline void NextIntersection::clear_shape() {
  shape_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NextIntersection::shape() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.shape)
  return shape_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NextIntersection::set_shape(const ::std::string& value) {
  
  shape_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.shape)
}
inline void NextIntersection::set_shape(const char* value) {
  
  shape_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Planning.NextIntersection.shape)
}
inline void NextIntersection::set_shape(const char* value, size_t size) {
  
  shape_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Planning.NextIntersection.shape)
}
inline ::std::string* NextIntersection::mutable_shape() {
  
  // @@protoc_insertion_point(field_mutable:Planning.NextIntersection.shape)
  return shape_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NextIntersection::release_shape() {
  // @@protoc_insertion_point(field_release:Planning.NextIntersection.shape)
  
  return shape_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NextIntersection::set_allocated_shape(::std::string* shape) {
  if (shape != NULL) {
    
  } else {
    
  }
  shape_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shape);
  // @@protoc_insertion_point(field_set_allocated:Planning.NextIntersection.shape)
}

// optional int32 lightsum = 13;
inline void NextIntersection::clear_lightsum() {
  lightsum_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::lightsum() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.lightsum)
  return lightsum_;
}
inline void NextIntersection::set_lightsum(::google::protobuf::int32 value) {
  
  lightsum_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.lightsum)
}

// optional int32 lightIdx = 14;
inline void NextIntersection::clear_lightidx() {
  lightidx_ = 0;
}
inline ::google::protobuf::int32 NextIntersection::lightidx() const {
  // @@protoc_insertion_point(field_get:Planning.NextIntersection.lightIdx)
  return lightidx_;
}
inline void NextIntersection::set_lightidx(::google::protobuf::int32 value) {
  
  lightidx_ = value;
  // @@protoc_insertion_point(field_set:Planning.NextIntersection.lightIdx)
}

// -------------------------------------------------------------------

// RoutingPointVec

// repeated .Planning.RoutingPoint RoutingPoints = 1;
inline int RoutingPointVec::routingpoints_size() const {
  return routingpoints_.size();
}
inline void RoutingPointVec::clear_routingpoints() {
  routingpoints_.Clear();
}
inline const ::Planning::RoutingPoint& RoutingPointVec::routingpoints(int index) const {
  // @@protoc_insertion_point(field_get:Planning.RoutingPointVec.RoutingPoints)
  return routingpoints_.Get(index);
}
inline ::Planning::RoutingPoint* RoutingPointVec::mutable_routingpoints(int index) {
  // @@protoc_insertion_point(field_mutable:Planning.RoutingPointVec.RoutingPoints)
  return routingpoints_.Mutable(index);
}
inline ::Planning::RoutingPoint* RoutingPointVec::add_routingpoints() {
  // @@protoc_insertion_point(field_add:Planning.RoutingPointVec.RoutingPoints)
  return routingpoints_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint >*
RoutingPointVec::mutable_routingpoints() {
  // @@protoc_insertion_point(field_mutable_list:Planning.RoutingPointVec.RoutingPoints)
  return &routingpoints_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Planning::RoutingPoint >&
RoutingPointVec::routingpoints() const {
  // @@protoc_insertion_point(field_list:Planning.RoutingPointVec.RoutingPoints)
  return routingpoints_;
}

// optional .Planning.NextIntersection nextIntersection = 2;
inline bool RoutingPointVec::has_nextintersection() const {
  return !_is_default_instance_ && nextintersection_ != NULL;
}
inline void RoutingPointVec::clear_nextintersection() {
  if (GetArenaNoVirtual() == NULL && nextintersection_ != NULL) delete nextintersection_;
  nextintersection_ = NULL;
}
inline const ::Planning::NextIntersection& RoutingPointVec::nextintersection() const {
  // @@protoc_insertion_point(field_get:Planning.RoutingPointVec.nextIntersection)
  return nextintersection_ != NULL ? *nextintersection_ : *default_instance_->nextintersection_;
}
inline ::Planning::NextIntersection* RoutingPointVec::mutable_nextintersection() {
  
  if (nextintersection_ == NULL) {
    nextintersection_ = new ::Planning::NextIntersection;
  }
  // @@protoc_insertion_point(field_mutable:Planning.RoutingPointVec.nextIntersection)
  return nextintersection_;
}
inline ::Planning::NextIntersection* RoutingPointVec::release_nextintersection() {
  // @@protoc_insertion_point(field_release:Planning.RoutingPointVec.nextIntersection)
  
  ::Planning::NextIntersection* temp = nextintersection_;
  nextintersection_ = NULL;
  return temp;
}
inline void RoutingPointVec::set_allocated_nextintersection(::Planning::NextIntersection* nextintersection) {
  delete nextintersection_;
  nextintersection_ = nextintersection;
  if (nextintersection) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Planning.RoutingPointVec.nextIntersection)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Planning

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RoutingMsg_2eproto__INCLUDED
