// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objectsvec.proto

#include "objectsvec.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_objects_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_objects_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ObjectsProto;
}  // namespace protobuf_objects_2eproto
namespace infopack {
class ObjectsVecDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ObjectsVec>
      _instance;
} _ObjectsVec_default_instance_;
}  // namespace infopack
namespace protobuf_objectsvec_2eproto {
static void InitDefaultsObjectsVec() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::infopack::_ObjectsVec_default_instance_;
    new (ptr) ::infopack::ObjectsVec();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::infopack::ObjectsVec::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ObjectsVec =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsObjectsVec}, {
      &protobuf_objects_2eproto::scc_info_ObjectsProto.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ObjectsVec.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::infopack::ObjectsVec, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::infopack::ObjectsVec, objmsg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::infopack::ObjectsVec, sensorid_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::infopack::ObjectsVec)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::infopack::_ObjectsVec_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "objectsvec.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020objectsvec.proto\022\010infopack\032\robjects.pr"
      "oto\"F\n\nObjectsVec\022&\n\006objMsg\030\001 \003(\0132\026.info"
      "pack.ObjectsProto\022\020\n\010sensorid\030\002 \001(\005b\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 123);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "objectsvec.proto", &protobuf_RegisterTypes);
  ::protobuf_objects_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_objectsvec_2eproto
namespace infopack {

// ===================================================================

void ObjectsVec::InitAsDefaultInstance() {
}
void ObjectsVec::clear_objmsg() {
  objmsg_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ObjectsVec::kObjMsgFieldNumber;
const int ObjectsVec::kSensoridFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ObjectsVec::ObjectsVec()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_objectsvec_2eproto::scc_info_ObjectsVec.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:infopack.ObjectsVec)
}
ObjectsVec::ObjectsVec(const ObjectsVec& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      objmsg_(from.objmsg_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sensorid_ = from.sensorid_;
  // @@protoc_insertion_point(copy_constructor:infopack.ObjectsVec)
}

void ObjectsVec::SharedCtor() {
  sensorid_ = 0;
}

ObjectsVec::~ObjectsVec() {
  // @@protoc_insertion_point(destructor:infopack.ObjectsVec)
  SharedDtor();
}

void ObjectsVec::SharedDtor() {
}

void ObjectsVec::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ObjectsVec::descriptor() {
  ::protobuf_objectsvec_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_objectsvec_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ObjectsVec& ObjectsVec::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_objectsvec_2eproto::scc_info_ObjectsVec.base);
  return *internal_default_instance();
}


void ObjectsVec::Clear() {
// @@protoc_insertion_point(message_clear_start:infopack.ObjectsVec)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  objmsg_.Clear();
  sensorid_ = 0;
  _internal_metadata_.Clear();
}

bool ObjectsVec::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:infopack.ObjectsVec)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .infopack.ObjectsProto objMsg = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_objmsg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 sensorid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sensorid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:infopack.ObjectsVec)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:infopack.ObjectsVec)
  return false;
#undef DO_
}

void ObjectsVec::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:infopack.ObjectsVec)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .infopack.ObjectsProto objMsg = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->objmsg_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->objmsg(static_cast<int>(i)),
      output);
  }

  // int32 sensorid = 2;
  if (this->sensorid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->sensorid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:infopack.ObjectsVec)
}

::google::protobuf::uint8* ObjectsVec::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:infopack.ObjectsVec)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .infopack.ObjectsProto objMsg = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->objmsg_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->objmsg(static_cast<int>(i)), deterministic, target);
  }

  // int32 sensorid = 2;
  if (this->sensorid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->sensorid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:infopack.ObjectsVec)
  return target;
}

size_t ObjectsVec::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:infopack.ObjectsVec)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .infopack.ObjectsProto objMsg = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->objmsg_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->objmsg(static_cast<int>(i)));
    }
  }

  // int32 sensorid = 2;
  if (this->sensorid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sensorid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ObjectsVec::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:infopack.ObjectsVec)
  GOOGLE_DCHECK_NE(&from, this);
  const ObjectsVec* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ObjectsVec>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:infopack.ObjectsVec)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:infopack.ObjectsVec)
    MergeFrom(*source);
  }
}

void ObjectsVec::MergeFrom(const ObjectsVec& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:infopack.ObjectsVec)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  objmsg_.MergeFrom(from.objmsg_);
  if (from.sensorid() != 0) {
    set_sensorid(from.sensorid());
  }
}

void ObjectsVec::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:infopack.ObjectsVec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjectsVec::CopyFrom(const ObjectsVec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infopack.ObjectsVec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjectsVec::IsInitialized() const {
  return true;
}

void ObjectsVec::Swap(ObjectsVec* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ObjectsVec::InternalSwap(ObjectsVec* other) {
  using std::swap;
  CastToBase(&objmsg_)->InternalSwap(CastToBase(&other->objmsg_));
  swap(sensorid_, other->sensorid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ObjectsVec::GetMetadata() const {
  protobuf_objectsvec_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_objectsvec_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace infopack
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::infopack::ObjectsVec* Arena::CreateMaybeMessage< ::infopack::ObjectsVec >(Arena* arena) {
  return Arena::CreateInternal< ::infopack::ObjectsVec >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
