// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objectsvec.proto

#ifndef PROTOBUF_INCLUDED_objectsvec_2eproto
#define PROTOBUF_INCLUDED_objectsvec_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "objects.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_objectsvec_2eproto 

namespace protobuf_objectsvec_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_objectsvec_2eproto
namespace infopack {
class ObjectsVec;
class ObjectsVecDefaultTypeInternal;
extern ObjectsVecDefaultTypeInternal _ObjectsVec_default_instance_;
}  // namespace infopack
namespace google {
namespace protobuf {
template<> ::infopack::ObjectsVec* Arena::CreateMaybeMessage<::infopack::ObjectsVec>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace infopack {

// ===================================================================

class ObjectsVec : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:infopack.ObjectsVec) */ {
 public:
  ObjectsVec();
  virtual ~ObjectsVec();

  ObjectsVec(const ObjectsVec& from);

  inline ObjectsVec& operator=(const ObjectsVec& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ObjectsVec(ObjectsVec&& from) noexcept
    : ObjectsVec() {
    *this = ::std::move(from);
  }

  inline ObjectsVec& operator=(ObjectsVec&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectsVec& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ObjectsVec* internal_default_instance() {
    return reinterpret_cast<const ObjectsVec*>(
               &_ObjectsVec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ObjectsVec* other);
  friend void swap(ObjectsVec& a, ObjectsVec& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ObjectsVec* New() const final {
    return CreateMaybeMessage<ObjectsVec>(NULL);
  }

  ObjectsVec* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ObjectsVec>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ObjectsVec& from);
  void MergeFrom(const ObjectsVec& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectsVec* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .infopack.ObjectsProto objMsg = 1;
  int objmsg_size() const;
  void clear_objmsg();
  static const int kObjMsgFieldNumber = 1;
  ::infopack::ObjectsProto* mutable_objmsg(int index);
  ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >*
      mutable_objmsg();
  const ::infopack::ObjectsProto& objmsg(int index) const;
  ::infopack::ObjectsProto* add_objmsg();
  const ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >&
      objmsg() const;

  // int32 sensorid = 2;
  void clear_sensorid();
  static const int kSensoridFieldNumber = 2;
  ::google::protobuf::int32 sensorid() const;
  void set_sensorid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:infopack.ObjectsVec)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto > objmsg_;
  ::google::protobuf::int32 sensorid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_objectsvec_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ObjectsVec

// repeated .infopack.ObjectsProto objMsg = 1;
inline int ObjectsVec::objmsg_size() const {
  return objmsg_.size();
}
inline ::infopack::ObjectsProto* ObjectsVec::mutable_objmsg(int index) {
  // @@protoc_insertion_point(field_mutable:infopack.ObjectsVec.objMsg)
  return objmsg_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >*
ObjectsVec::mutable_objmsg() {
  // @@protoc_insertion_point(field_mutable_list:infopack.ObjectsVec.objMsg)
  return &objmsg_;
}
inline const ::infopack::ObjectsProto& ObjectsVec::objmsg(int index) const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsVec.objMsg)
  return objmsg_.Get(index);
}
inline ::infopack::ObjectsProto* ObjectsVec::add_objmsg() {
  // @@protoc_insertion_point(field_add:infopack.ObjectsVec.objMsg)
  return objmsg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >&
ObjectsVec::objmsg() const {
  // @@protoc_insertion_point(field_list:infopack.ObjectsVec.objMsg)
  return objmsg_;
}

// int32 sensorid = 2;
inline void ObjectsVec::clear_sensorid() {
  sensorid_ = 0;
}
inline ::google::protobuf::int32 ObjectsVec::sensorid() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsVec.sensorid)
  return sensorid_;
}
inline void ObjectsVec::set_sensorid(::google::protobuf::int32 value) {
  
  sensorid_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsVec.sensorid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_objectsvec_2eproto
