// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic_light.proto

#ifndef PROTOBUF_INCLUDED_traffic_5flight_2eproto
#define PROTOBUF_INCLUDED_traffic_5flight_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_traffic_5flight_2eproto 

namespace protobuf_traffic_5flight_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_traffic_5flight_2eproto
namespace infopack {
class TrafficLight;
class TrafficLightDefaultTypeInternal;
extern TrafficLightDefaultTypeInternal _TrafficLight_default_instance_;
}  // namespace infopack
namespace google {
namespace protobuf {
template<> ::infopack::TrafficLight* Arena::CreateMaybeMessage<::infopack::TrafficLight>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace infopack {

enum TrafficLight_State {
  TrafficLight_State_RED_LIGHT = 0,
  TrafficLight_State_YELLOW_LIGHT = 1,
  TrafficLight_State_GREEN_LIGHT = 2,
  TrafficLight_State_TrafficLight_State_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  TrafficLight_State_TrafficLight_State_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool TrafficLight_State_IsValid(int value);
const TrafficLight_State TrafficLight_State_State_MIN = TrafficLight_State_RED_LIGHT;
const TrafficLight_State TrafficLight_State_State_MAX = TrafficLight_State_GREEN_LIGHT;
const int TrafficLight_State_State_ARRAYSIZE = TrafficLight_State_State_MAX + 1;

const ::google::protobuf::EnumDescriptor* TrafficLight_State_descriptor();
inline const ::std::string& TrafficLight_State_Name(TrafficLight_State value) {
  return ::google::protobuf::internal::NameOfEnum(
    TrafficLight_State_descriptor(), value);
}
inline bool TrafficLight_State_Parse(
    const ::std::string& name, TrafficLight_State* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TrafficLight_State>(
    TrafficLight_State_descriptor(), name, value);
}
// ===================================================================

class TrafficLight : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:infopack.TrafficLight) */ {
 public:
  TrafficLight();
  virtual ~TrafficLight();

  TrafficLight(const TrafficLight& from);

  inline TrafficLight& operator=(const TrafficLight& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TrafficLight(TrafficLight&& from) noexcept
    : TrafficLight() {
    *this = ::std::move(from);
  }

  inline TrafficLight& operator=(TrafficLight&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TrafficLight& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TrafficLight* internal_default_instance() {
    return reinterpret_cast<const TrafficLight*>(
               &_TrafficLight_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TrafficLight* other);
  friend void swap(TrafficLight& a, TrafficLight& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TrafficLight* New() const final {
    return CreateMaybeMessage<TrafficLight>(NULL);
  }

  TrafficLight* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TrafficLight>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TrafficLight& from);
  void MergeFrom(const TrafficLight& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrafficLight* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef TrafficLight_State State;
  static const State RED_LIGHT =
    TrafficLight_State_RED_LIGHT;
  static const State YELLOW_LIGHT =
    TrafficLight_State_YELLOW_LIGHT;
  static const State GREEN_LIGHT =
    TrafficLight_State_GREEN_LIGHT;
  static inline bool State_IsValid(int value) {
    return TrafficLight_State_IsValid(value);
  }
  static const State State_MIN =
    TrafficLight_State_State_MIN;
  static const State State_MAX =
    TrafficLight_State_State_MAX;
  static const int State_ARRAYSIZE =
    TrafficLight_State_State_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  State_descriptor() {
    return TrafficLight_State_descriptor();
  }
  static inline const ::std::string& State_Name(State value) {
    return TrafficLight_State_Name(value);
  }
  static inline bool State_Parse(const ::std::string& name,
      State* value) {
    return TrafficLight_State_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // bool active = 1;
  void clear_active();
  static const int kActiveFieldNumber = 1;
  bool active() const;
  void set_active(bool value);

  // .infopack.TrafficLight.State state = 2;
  void clear_state();
  static const int kStateFieldNumber = 2;
  ::infopack::TrafficLight_State state() const;
  void set_state(::infopack::TrafficLight_State value);

  // double remaining_time = 3;
  void clear_remaining_time();
  static const int kRemainingTimeFieldNumber = 3;
  double remaining_time() const;
  void set_remaining_time(double value);

  // double lane_length_before_intersection = 4;
  void clear_lane_length_before_intersection();
  static const int kLaneLengthBeforeIntersectionFieldNumber = 4;
  double lane_length_before_intersection() const;
  void set_lane_length_before_intersection(double value);

  // @@protoc_insertion_point(class_scope:infopack.TrafficLight)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool active_;
  int state_;
  double remaining_time_;
  double lane_length_before_intersection_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_traffic_5flight_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TrafficLight

// bool active = 1;
inline void TrafficLight::clear_active() {
  active_ = false;
}
inline bool TrafficLight::active() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.active)
  return active_;
}
inline void TrafficLight::set_active(bool value) {
  
  active_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.active)
}

// .infopack.TrafficLight.State state = 2;
inline void TrafficLight::clear_state() {
  state_ = 0;
}
inline ::infopack::TrafficLight_State TrafficLight::state() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.state)
  return static_cast< ::infopack::TrafficLight_State >(state_);
}
inline void TrafficLight::set_state(::infopack::TrafficLight_State value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.state)
}

// double remaining_time = 3;
inline void TrafficLight::clear_remaining_time() {
  remaining_time_ = 0;
}
inline double TrafficLight::remaining_time() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.remaining_time)
  return remaining_time_;
}
inline void TrafficLight::set_remaining_time(double value) {
  
  remaining_time_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.remaining_time)
}

// double lane_length_before_intersection = 4;
inline void TrafficLight::clear_lane_length_before_intersection() {
  lane_length_before_intersection_ = 0;
}
inline double TrafficLight::lane_length_before_intersection() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.lane_length_before_intersection)
  return lane_length_before_intersection_;
}
inline void TrafficLight::set_lane_length_before_intersection(double value) {
  
  lane_length_before_intersection_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.lane_length_before_intersection)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::infopack::TrafficLight_State> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::infopack::TrafficLight_State>() {
  return ::infopack::TrafficLight_State_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_traffic_5flight_2eproto
