// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imu/imu.proto

#ifndef PROTOBUF_INCLUDED_Imu_2fimu_2eproto
#define PROTOBUF_INCLUDED_Imu_2fimu_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Imu_2fimu_2eproto 

namespace protobuf_Imu_2fimu_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Imu_2fimu_2eproto
namespace IMU {
class Imu;
class ImuDefaultTypeInternal;
extern ImuDefaultTypeInternal _Imu_default_instance_;
}  // namespace IMU
namespace google {
namespace protobuf {
template<> ::IMU::Imu* Arena::CreateMaybeMessage<::IMU::Imu>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace IMU {

// ===================================================================

class Imu : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:IMU.Imu) */ {
 public:
  Imu();
  virtual ~Imu();

  Imu(const Imu& from);

  inline Imu& operator=(const Imu& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Imu(Imu&& from) noexcept
    : Imu() {
    *this = ::std::move(from);
  }

  inline Imu& operator=(Imu&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Imu& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Imu* internal_default_instance() {
    return reinterpret_cast<const Imu*>(
               &_Imu_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Imu* other);
  friend void swap(Imu& a, Imu& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Imu* New() const final {
    return CreateMaybeMessage<Imu>(NULL);
  }

  Imu* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Imu>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Imu& from);
  void MergeFrom(const Imu& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Imu* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double longitude = 1;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 1;
  double longitude() const;
  void set_longitude(double value);

  // double latitude = 2;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 2;
  double latitude() const;
  void set_latitude(double value);

  // double gaussX = 3;
  void clear_gaussx();
  static const int kGaussXFieldNumber = 3;
  double gaussx() const;
  void set_gaussx(double value);

  // double gaussY = 4;
  void clear_gaussy();
  static const int kGaussYFieldNumber = 4;
  double gaussy() const;
  void set_gaussy(double value);

  // double time = 6;
  void clear_time();
  static const int kTimeFieldNumber = 6;
  double time() const;
  void set_time(double value);

  // double velocity = 7;
  void clear_velocity();
  static const int kVelocityFieldNumber = 7;
  double velocity() const;
  void set_velocity(double value);

  // double yaw = 8;
  void clear_yaw();
  static const int kYawFieldNumber = 8;
  double yaw() const;
  void set_yaw(double value);

  // int32 gpsValid = 5;
  void clear_gpsvalid();
  static const int kGpsValidFieldNumber = 5;
  ::google::protobuf::int32 gpsvalid() const;
  void set_gpsvalid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:IMU.Imu)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double longitude_;
  double latitude_;
  double gaussx_;
  double gaussy_;
  double time_;
  double velocity_;
  double yaw_;
  ::google::protobuf::int32 gpsvalid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Imu_2fimu_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Imu

// double longitude = 1;
inline void Imu::clear_longitude() {
  longitude_ = 0;
}
inline double Imu::longitude() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.longitude)
  return longitude_;
}
inline void Imu::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.longitude)
}

// double latitude = 2;
inline void Imu::clear_latitude() {
  latitude_ = 0;
}
inline double Imu::latitude() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.latitude)
  return latitude_;
}
inline void Imu::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.latitude)
}

// double gaussX = 3;
inline void Imu::clear_gaussx() {
  gaussx_ = 0;
}
inline double Imu::gaussx() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gaussX)
  return gaussx_;
}
inline void Imu::set_gaussx(double value) {
  
  gaussx_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gaussX)
}

// double gaussY = 4;
inline void Imu::clear_gaussy() {
  gaussy_ = 0;
}
inline double Imu::gaussy() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gaussY)
  return gaussy_;
}
inline void Imu::set_gaussy(double value) {
  
  gaussy_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gaussY)
}

// int32 gpsValid = 5;
inline void Imu::clear_gpsvalid() {
  gpsvalid_ = 0;
}
inline ::google::protobuf::int32 Imu::gpsvalid() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gpsValid)
  return gpsvalid_;
}
inline void Imu::set_gpsvalid(::google::protobuf::int32 value) {
  
  gpsvalid_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gpsValid)
}

// double time = 6;
inline void Imu::clear_time() {
  time_ = 0;
}
inline double Imu::time() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.time)
  return time_;
}
inline void Imu::set_time(double value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.time)
}

// double velocity = 7;
inline void Imu::clear_velocity() {
  velocity_ = 0;
}
inline double Imu::velocity() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.velocity)
  return velocity_;
}
inline void Imu::set_velocity(double value) {
  
  velocity_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.velocity)
}

// double yaw = 8;
inline void Imu::clear_yaw() {
  yaw_ = 0;
}
inline double Imu::yaw() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.yaw)
  return yaw_;
}
inline void Imu::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.yaw)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace IMU

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Imu_2fimu_2eproto
