#roadmap dir/file and statrpoint file
stratpointFile: /home/ran/workspace/projects/functional_software_previous_work/simulator_software/2024cbdes_model_version/thicvPilot_0924_all/planningFigure/mapMsg/stopPoint.yaml  
 
