ssmPubAddress=tcp://127.0.0.1:5581 
spartPubAddress=tcp://127.0.0.1:5583 
posSubAddress=tcp://127.0.0.1:5003
planningSubAddress=tcp://127.0.0.1:5582
serverReqAddress=tcp://58.210.18.98:5514

ssmWriteFlag=1
spartWriteFlag=0
vehiclePosWriteFlag=0
planningWriteFlag=0

ssmFilePath=../logs/participants_data.csv
spartFilePath=../logs/light_data.txt
vposFilePath=../logs/vehicle_pos_data.txt
vplanningFilePath=../logs/vehicle_planning_data.txt
