// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imu.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_imu_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_imu_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_imu_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_imu_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_imu_2eproto;
namespace pc {
class Imu;
struct ImuDefaultTypeInternal;
extern ImuDefaultTypeInternal _Imu_default_instance_;
}  // namespace pc
PROTOBUF_NAMESPACE_OPEN
template<> ::pc::Imu* Arena::CreateMaybeMessage<::pc::Imu>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pc {

// ===================================================================

class Imu final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pc.Imu) */ {
 public:
  inline Imu() : Imu(nullptr) {}
  ~Imu() override;
  explicit PROTOBUF_CONSTEXPR Imu(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Imu(const Imu& from);
  Imu(Imu&& from) noexcept
    : Imu() {
    *this = ::std::move(from);
  }

  inline Imu& operator=(const Imu& from) {
    CopyFrom(from);
    return *this;
  }
  inline Imu& operator=(Imu&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Imu& default_instance() {
    return *internal_default_instance();
  }
  static inline const Imu* internal_default_instance() {
    return reinterpret_cast<const Imu*>(
               &_Imu_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Imu& a, Imu& b) {
    a.Swap(&b);
  }
  inline void Swap(Imu* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Imu* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Imu* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Imu>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Imu& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Imu& from) {
    Imu::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Imu* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pc.Imu";
  }
  protected:
  explicit Imu(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLongitudeFieldNumber = 1,
    kLatitudeFieldNumber = 2,
    kGaussXFieldNumber = 3,
    kGaussYFieldNumber = 4,
    kTimeFieldNumber = 6,
    kVelocityFieldNumber = 7,
    kYawFieldNumber = 8,
    kGpsValidFieldNumber = 5,
  };
  // double longitude = 1;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // double latitude = 2;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // double gaussX = 3;
  void clear_gaussx();
  double gaussx() const;
  void set_gaussx(double value);
  private:
  double _internal_gaussx() const;
  void _internal_set_gaussx(double value);
  public:

  // double gaussY = 4;
  void clear_gaussy();
  double gaussy() const;
  void set_gaussy(double value);
  private:
  double _internal_gaussy() const;
  void _internal_set_gaussy(double value);
  public:

  // double time = 6;
  void clear_time();
  double time() const;
  void set_time(double value);
  private:
  double _internal_time() const;
  void _internal_set_time(double value);
  public:

  // double velocity = 7;
  void clear_velocity();
  double velocity() const;
  void set_velocity(double value);
  private:
  double _internal_velocity() const;
  void _internal_set_velocity(double value);
  public:

  // double yaw = 8;
  void clear_yaw();
  double yaw() const;
  void set_yaw(double value);
  private:
  double _internal_yaw() const;
  void _internal_set_yaw(double value);
  public:

  // int32 gpsValid = 5;
  void clear_gpsvalid();
  int32_t gpsvalid() const;
  void set_gpsvalid(int32_t value);
  private:
  int32_t _internal_gpsvalid() const;
  void _internal_set_gpsvalid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pc.Imu)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double longitude_;
    double latitude_;
    double gaussx_;
    double gaussy_;
    double time_;
    double velocity_;
    double yaw_;
    int32_t gpsvalid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_imu_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Imu

// double longitude = 1;
inline void Imu::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline double Imu::_internal_longitude() const {
  return _impl_.longitude_;
}
inline double Imu::longitude() const {
  // @@protoc_insertion_point(field_get:pc.Imu.longitude)
  return _internal_longitude();
}
inline void Imu::_internal_set_longitude(double value) {
  
  _impl_.longitude_ = value;
}
inline void Imu::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:pc.Imu.longitude)
}

// double latitude = 2;
inline void Imu::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline double Imu::_internal_latitude() const {
  return _impl_.latitude_;
}
inline double Imu::latitude() const {
  // @@protoc_insertion_point(field_get:pc.Imu.latitude)
  return _internal_latitude();
}
inline void Imu::_internal_set_latitude(double value) {
  
  _impl_.latitude_ = value;
}
inline void Imu::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:pc.Imu.latitude)
}

// double gaussX = 3;
inline void Imu::clear_gaussx() {
  _impl_.gaussx_ = 0;
}
inline double Imu::_internal_gaussx() const {
  return _impl_.gaussx_;
}
inline double Imu::gaussx() const {
  // @@protoc_insertion_point(field_get:pc.Imu.gaussX)
  return _internal_gaussx();
}
inline void Imu::_internal_set_gaussx(double value) {
  
  _impl_.gaussx_ = value;
}
inline void Imu::set_gaussx(double value) {
  _internal_set_gaussx(value);
  // @@protoc_insertion_point(field_set:pc.Imu.gaussX)
}

// double gaussY = 4;
inline void Imu::clear_gaussy() {
  _impl_.gaussy_ = 0;
}
inline double Imu::_internal_gaussy() const {
  return _impl_.gaussy_;
}
inline double Imu::gaussy() const {
  // @@protoc_insertion_point(field_get:pc.Imu.gaussY)
  return _internal_gaussy();
}
inline void Imu::_internal_set_gaussy(double value) {
  
  _impl_.gaussy_ = value;
}
inline void Imu::set_gaussy(double value) {
  _internal_set_gaussy(value);
  // @@protoc_insertion_point(field_set:pc.Imu.gaussY)
}

// int32 gpsValid = 5;
inline void Imu::clear_gpsvalid() {
  _impl_.gpsvalid_ = 0;
}
inline int32_t Imu::_internal_gpsvalid() const {
  return _impl_.gpsvalid_;
}
inline int32_t Imu::gpsvalid() const {
  // @@protoc_insertion_point(field_get:pc.Imu.gpsValid)
  return _internal_gpsvalid();
}
inline void Imu::_internal_set_gpsvalid(int32_t value) {
  
  _impl_.gpsvalid_ = value;
}
inline void Imu::set_gpsvalid(int32_t value) {
  _internal_set_gpsvalid(value);
  // @@protoc_insertion_point(field_set:pc.Imu.gpsValid)
}

// double time = 6;
inline void Imu::clear_time() {
  _impl_.time_ = 0;
}
inline double Imu::_internal_time() const {
  return _impl_.time_;
}
inline double Imu::time() const {
  // @@protoc_insertion_point(field_get:pc.Imu.time)
  return _internal_time();
}
inline void Imu::_internal_set_time(double value) {
  
  _impl_.time_ = value;
}
inline void Imu::set_time(double value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:pc.Imu.time)
}

// double velocity = 7;
inline void Imu::clear_velocity() {
  _impl_.velocity_ = 0;
}
inline double Imu::_internal_velocity() const {
  return _impl_.velocity_;
}
inline double Imu::velocity() const {
  // @@protoc_insertion_point(field_get:pc.Imu.velocity)
  return _internal_velocity();
}
inline void Imu::_internal_set_velocity(double value) {
  
  _impl_.velocity_ = value;
}
inline void Imu::set_velocity(double value) {
  _internal_set_velocity(value);
  // @@protoc_insertion_point(field_set:pc.Imu.velocity)
}

// double yaw = 8;
inline void Imu::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline double Imu::_internal_yaw() const {
  return _impl_.yaw_;
}
inline double Imu::yaw() const {
  // @@protoc_insertion_point(field_get:pc.Imu.yaw)
  return _internal_yaw();
}
inline void Imu::_internal_set_yaw(double value) {
  
  _impl_.yaw_ = value;
}
inline void Imu::set_yaw(double value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:pc.Imu.yaw)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_imu_2eproto
