// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ui.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ui_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ui_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ui_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ui_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ui_2eproto;
namespace ui {
class Cv;
struct CvDefaultTypeInternal;
extern CvDefaultTypeInternal _Cv_default_instance_;
class Gnss;
struct GnssDefaultTypeInternal;
extern GnssDefaultTypeInternal _Gnss_default_instance_;
class Imu;
struct ImuDefaultTypeInternal;
extern ImuDefaultTypeInternal _Imu_default_instance_;
class Iov;
struct IovDefaultTypeInternal;
extern IovDefaultTypeInternal _Iov_default_instance_;
class Posture;
struct PostureDefaultTypeInternal;
extern PostureDefaultTypeInternal _Posture_default_instance_;
class UiPad2VData;
struct UiPad2VDataDefaultTypeInternal;
extern UiPad2VDataDefaultTypeInternal _UiPad2VData_default_instance_;
class UiV2PadData;
struct UiV2PadDataDefaultTypeInternal;
extern UiV2PadDataDefaultTypeInternal _UiV2PadData_default_instance_;
}  // namespace ui
PROTOBUF_NAMESPACE_OPEN
template<> ::ui::Cv* Arena::CreateMaybeMessage<::ui::Cv>(Arena*);
template<> ::ui::Gnss* Arena::CreateMaybeMessage<::ui::Gnss>(Arena*);
template<> ::ui::Imu* Arena::CreateMaybeMessage<::ui::Imu>(Arena*);
template<> ::ui::Iov* Arena::CreateMaybeMessage<::ui::Iov>(Arena*);
template<> ::ui::Posture* Arena::CreateMaybeMessage<::ui::Posture>(Arena*);
template<> ::ui::UiPad2VData* Arena::CreateMaybeMessage<::ui::UiPad2VData>(Arena*);
template<> ::ui::UiV2PadData* Arena::CreateMaybeMessage<::ui::UiV2PadData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ui {

// ===================================================================

class UiPad2VData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ui.UiPad2VData) */ {
 public:
  inline UiPad2VData() : UiPad2VData(nullptr) {}
  ~UiPad2VData() override;
  explicit PROTOBUF_CONSTEXPR UiPad2VData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UiPad2VData(const UiPad2VData& from);
  UiPad2VData(UiPad2VData&& from) noexcept
    : UiPad2VData() {
    *this = ::std::move(from);
  }

  inline UiPad2VData& operator=(const UiPad2VData& from) {
    CopyFrom(from);
    return *this;
  }
  inline UiPad2VData& operator=(UiPad2VData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UiPad2VData& default_instance() {
    return *internal_default_instance();
  }
  static inline const UiPad2VData* internal_default_instance() {
    return reinterpret_cast<const UiPad2VData*>(
               &_UiPad2VData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UiPad2VData& a, UiPad2VData& b) {
    a.Swap(&b);
  }
  inline void Swap(UiPad2VData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UiPad2VData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UiPad2VData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UiPad2VData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UiPad2VData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UiPad2VData& from) {
    UiPad2VData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UiPad2VData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ui.UiPad2VData";
  }
  protected:
  explicit UiPad2VData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBStopFlagFieldNumber = 1,
    kBSpeedOffFieldNumber = 2,
    kBSteeringOffFieldNumber = 3,
    kBIsValidFieldNumber = 4,
    kSTargetPathFieldNumber = 6,
    kBConfig1FieldNumber = 5,
    kBIsAliveFieldNumber = 7,
  };
  // bool b_stopFlag = 1;
  void clear_b_stopflag();
  bool b_stopflag() const;
  void set_b_stopflag(bool value);
  private:
  bool _internal_b_stopflag() const;
  void _internal_set_b_stopflag(bool value);
  public:

  // bool b_speedOff = 2;
  void clear_b_speedoff();
  bool b_speedoff() const;
  void set_b_speedoff(bool value);
  private:
  bool _internal_b_speedoff() const;
  void _internal_set_b_speedoff(bool value);
  public:

  // bool b_steeringOff = 3;
  void clear_b_steeringoff();
  bool b_steeringoff() const;
  void set_b_steeringoff(bool value);
  private:
  bool _internal_b_steeringoff() const;
  void _internal_set_b_steeringoff(bool value);
  public:

  // bool b_isValid = 4;
  void clear_b_isvalid();
  bool b_isvalid() const;
  void set_b_isvalid(bool value);
  private:
  bool _internal_b_isvalid() const;
  void _internal_set_b_isvalid(bool value);
  public:

  // int32 s_targetPath = 6;
  void clear_s_targetpath();
  int32_t s_targetpath() const;
  void set_s_targetpath(int32_t value);
  private:
  int32_t _internal_s_targetpath() const;
  void _internal_set_s_targetpath(int32_t value);
  public:

  // bool b_config1 = 5;
  void clear_b_config1();
  bool b_config1() const;
  void set_b_config1(bool value);
  private:
  bool _internal_b_config1() const;
  void _internal_set_b_config1(bool value);
  public:

  // bool b_isAlive = 7;
  void clear_b_isalive();
  bool b_isalive() const;
  void set_b_isalive(bool value);
  private:
  bool _internal_b_isalive() const;
  void _internal_set_b_isalive(bool value);
  public:

  // @@protoc_insertion_point(class_scope:ui.UiPad2VData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool b_stopflag_;
    bool b_speedoff_;
    bool b_steeringoff_;
    bool b_isvalid_;
    int32_t s_targetpath_;
    bool b_config1_;
    bool b_isalive_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ui_2eproto;
};
// -------------------------------------------------------------------

class Imu final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ui.Imu) */ {
 public:
  inline Imu() : Imu(nullptr) {}
  ~Imu() override;
  explicit PROTOBUF_CONSTEXPR Imu(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Imu(const Imu& from);
  Imu(Imu&& from) noexcept
    : Imu() {
    *this = ::std::move(from);
  }

  inline Imu& operator=(const Imu& from) {
    CopyFrom(from);
    return *this;
  }
  inline Imu& operator=(Imu&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Imu& default_instance() {
    return *internal_default_instance();
  }
  static inline const Imu* internal_default_instance() {
    return reinterpret_cast<const Imu*>(
               &_Imu_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Imu& a, Imu& b) {
    a.Swap(&b);
  }
  inline void Swap(Imu* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Imu* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Imu* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Imu>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Imu& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Imu& from) {
    Imu::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Imu* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ui.Imu";
  }
  protected:
  explicit Imu(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
    kVelocityFieldNumber = 2,
    kRollFieldNumber = 3,
    kYawFieldNumber = 4,
    kPitchFieldNumber = 5,
    kLatitudeFieldNumber = 8,
    kLongitudeFieldNumber = 9,
    kGaussXFieldNumber = 10,
    kGaussYFieldNumber = 11,
    kYawRateFieldNumber = 12,
    kBIsValidFieldNumber = 6,
    kBGpsValidFieldNumber = 7,
    kBIsAliveFieldNumber = 13,
  };
  // double time = 1;
  void clear_time();
  double time() const;
  void set_time(double value);
  private:
  double _internal_time() const;
  void _internal_set_time(double value);
  public:

  // double velocity = 2;
  void clear_velocity();
  double velocity() const;
  void set_velocity(double value);
  private:
  double _internal_velocity() const;
  void _internal_set_velocity(double value);
  public:

  // double roll = 3;
  void clear_roll();
  double roll() const;
  void set_roll(double value);
  private:
  double _internal_roll() const;
  void _internal_set_roll(double value);
  public:

  // double yaw = 4;
  void clear_yaw();
  double yaw() const;
  void set_yaw(double value);
  private:
  double _internal_yaw() const;
  void _internal_set_yaw(double value);
  public:

  // double pitch = 5;
  void clear_pitch();
  double pitch() const;
  void set_pitch(double value);
  private:
  double _internal_pitch() const;
  void _internal_set_pitch(double value);
  public:

  // double latitude = 8;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // double longitude = 9;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // double gaussX = 10;
  void clear_gaussx();
  double gaussx() const;
  void set_gaussx(double value);
  private:
  double _internal_gaussx() const;
  void _internal_set_gaussx(double value);
  public:

  // double gaussY = 11;
  void clear_gaussy();
  double gaussy() const;
  void set_gaussy(double value);
  private:
  double _internal_gaussy() const;
  void _internal_set_gaussy(double value);
  public:

  // double yawRate = 12;
  void clear_yawrate();
  double yawrate() const;
  void set_yawrate(double value);
  private:
  double _internal_yawrate() const;
  void _internal_set_yawrate(double value);
  public:

  // bool b_isValid = 6;
  void clear_b_isvalid();
  bool b_isvalid() const;
  void set_b_isvalid(bool value);
  private:
  bool _internal_b_isvalid() const;
  void _internal_set_b_isvalid(bool value);
  public:

  // bool b_gpsValid = 7;
  void clear_b_gpsvalid();
  bool b_gpsvalid() const;
  void set_b_gpsvalid(bool value);
  private:
  bool _internal_b_gpsvalid() const;
  void _internal_set_b_gpsvalid(bool value);
  public:

  // bool b_isAlive = 13;
  void clear_b_isalive();
  bool b_isalive() const;
  void set_b_isalive(bool value);
  private:
  bool _internal_b_isalive() const;
  void _internal_set_b_isalive(bool value);
  public:

  // @@protoc_insertion_point(class_scope:ui.Imu)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double time_;
    double velocity_;
    double roll_;
    double yaw_;
    double pitch_;
    double latitude_;
    double longitude_;
    double gaussx_;
    double gaussy_;
    double yawrate_;
    bool b_isvalid_;
    bool b_gpsvalid_;
    bool b_isalive_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ui_2eproto;
};
// -------------------------------------------------------------------

class Gnss final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ui.Gnss) */ {
 public:
  inline Gnss() : Gnss(nullptr) {}
  ~Gnss() override;
  explicit PROTOBUF_CONSTEXPR Gnss(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Gnss(const Gnss& from);
  Gnss(Gnss&& from) noexcept
    : Gnss() {
    *this = ::std::move(from);
  }

  inline Gnss& operator=(const Gnss& from) {
    CopyFrom(from);
    return *this;
  }
  inline Gnss& operator=(Gnss&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Gnss& default_instance() {
    return *internal_default_instance();
  }
  static inline const Gnss* internal_default_instance() {
    return reinterpret_cast<const Gnss*>(
               &_Gnss_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Gnss& a, Gnss& b) {
    a.Swap(&b);
  }
  inline void Swap(Gnss* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Gnss* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Gnss* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Gnss>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Gnss& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Gnss& from) {
    Gnss::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Gnss* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ui.Gnss";
  }
  protected:
  explicit Gnss(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLongitudeFieldNumber = 1,
    kLatitudeFieldNumber = 2,
    kGaussXFieldNumber = 3,
    kGaussYFieldNumber = 4,
    kYawFieldNumber = 5,
    kUtcSecondFieldNumber = 7,
    kGpsQualityFieldNumber = 6,
    kBIsValidFieldNumber = 8,
    kBIsDiffitialFieldNumber = 9,
    kBIsAliveFieldNumber = 10,
  };
  // double longitude = 1;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // double latitude = 2;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // double gaussX = 3;
  void clear_gaussx();
  double gaussx() const;
  void set_gaussx(double value);
  private:
  double _internal_gaussx() const;
  void _internal_set_gaussx(double value);
  public:

  // double gaussY = 4;
  void clear_gaussy();
  double gaussy() const;
  void set_gaussy(double value);
  private:
  double _internal_gaussy() const;
  void _internal_set_gaussy(double value);
  public:

  // double yaw = 5;
  void clear_yaw();
  double yaw() const;
  void set_yaw(double value);
  private:
  double _internal_yaw() const;
  void _internal_set_yaw(double value);
  public:

  // double utc_second = 7;
  void clear_utc_second();
  double utc_second() const;
  void set_utc_second(double value);
  private:
  double _internal_utc_second() const;
  void _internal_set_utc_second(double value);
  public:

  // int32 gpsQuality = 6;
  void clear_gpsquality();
  int32_t gpsquality() const;
  void set_gpsquality(int32_t value);
  private:
  int32_t _internal_gpsquality() const;
  void _internal_set_gpsquality(int32_t value);
  public:

  // bool b_isValid = 8;
  void clear_b_isvalid();
  bool b_isvalid() const;
  void set_b_isvalid(bool value);
  private:
  bool _internal_b_isvalid() const;
  void _internal_set_b_isvalid(bool value);
  public:

  // bool b_isDiffitial = 9;
  void clear_b_isdiffitial();
  bool b_isdiffitial() const;
  void set_b_isdiffitial(bool value);
  private:
  bool _internal_b_isdiffitial() const;
  void _internal_set_b_isdiffitial(bool value);
  public:

  // bool b_isAlive = 10;
  void clear_b_isalive();
  bool b_isalive() const;
  void set_b_isalive(bool value);
  private:
  bool _internal_b_isalive() const;
  void _internal_set_b_isalive(bool value);
  public:

  // @@protoc_insertion_point(class_scope:ui.Gnss)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double longitude_;
    double latitude_;
    double gaussx_;
    double gaussy_;
    double yaw_;
    double utc_second_;
    int32_t gpsquality_;
    bool b_isvalid_;
    bool b_isdiffitial_;
    bool b_isalive_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ui_2eproto;
};
// -------------------------------------------------------------------

class Posture final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ui.Posture) */ {
 public:
  inline Posture() : Posture(nullptr) {}
  ~Posture() override;
  explicit PROTOBUF_CONSTEXPR Posture(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Posture(const Posture& from);
  Posture(Posture&& from) noexcept
    : Posture() {
    *this = ::std::move(from);
  }

  inline Posture& operator=(const Posture& from) {
    CopyFrom(from);
    return *this;
  }
  inline Posture& operator=(Posture&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Posture& default_instance() {
    return *internal_default_instance();
  }
  static inline const Posture* internal_default_instance() {
    return reinterpret_cast<const Posture*>(
               &_Posture_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Posture& a, Posture& b) {
    a.Swap(&b);
  }
  inline void Swap(Posture* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Posture* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Posture* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Posture>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Posture& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Posture& from) {
    Posture::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Posture* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ui.Posture";
  }
  protected:
  explicit Posture(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImuFieldNumber = 1,
    kGnssFieldNumber = 2,
    kBIsAliveFieldNumber = 3,
  };
  // repeated .ui.Imu imu = 1;
  int imu_size() const;
  private:
  int _internal_imu_size() const;
  public:
  void clear_imu();
  ::ui::Imu* mutable_imu(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Imu >*
      mutable_imu();
  private:
  const ::ui::Imu& _internal_imu(int index) const;
  ::ui::Imu* _internal_add_imu();
  public:
  const ::ui::Imu& imu(int index) const;
  ::ui::Imu* add_imu();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Imu >&
      imu() const;

  // repeated .ui.Gnss gnss = 2;
  int gnss_size() const;
  private:
  int _internal_gnss_size() const;
  public:
  void clear_gnss();
  ::ui::Gnss* mutable_gnss(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Gnss >*
      mutable_gnss();
  private:
  const ::ui::Gnss& _internal_gnss(int index) const;
  ::ui::Gnss* _internal_add_gnss();
  public:
  const ::ui::Gnss& gnss(int index) const;
  ::ui::Gnss* add_gnss();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Gnss >&
      gnss() const;

  // bool b_isAlive = 3;
  void clear_b_isalive();
  bool b_isalive() const;
  void set_b_isalive(bool value);
  private:
  bool _internal_b_isalive() const;
  void _internal_set_b_isalive(bool value);
  public:

  // @@protoc_insertion_point(class_scope:ui.Posture)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Imu > imu_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Gnss > gnss_;
    bool b_isalive_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ui_2eproto;
};
// -------------------------------------------------------------------

class Iov final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ui.Iov) */ {
 public:
  inline Iov() : Iov(nullptr) {}
  ~Iov() override;
  explicit PROTOBUF_CONSTEXPR Iov(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Iov(const Iov& from);
  Iov(Iov&& from) noexcept
    : Iov() {
    *this = ::std::move(from);
  }

  inline Iov& operator=(const Iov& from) {
    CopyFrom(from);
    return *this;
  }
  inline Iov& operator=(Iov&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Iov& default_instance() {
    return *internal_default_instance();
  }
  static inline const Iov* internal_default_instance() {
    return reinterpret_cast<const Iov*>(
               &_Iov_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Iov& a, Iov& b) {
    a.Swap(&b);
  }
  inline void Swap(Iov* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Iov* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Iov* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Iov>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Iov& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Iov& from) {
    Iov::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Iov* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ui.Iov";
  }
  protected:
  explicit Iov(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVehicleIdFieldNumber = 4,
    kBIsValidFieldNumber = 1,
    kBIsAliveFieldNumber = 2,
    kBVehicleValidFieldNumber = 3,
    kBLightValidFieldNumber = 11,
    kVehicleGaussXFieldNumber = 6,
    kVehicleGaussYFieldNumber = 7,
    kVehicleSpeedFieldNumber = 8,
    kVehicleTypeFieldNumber = 5,
    kLightPhaseFieldNumber = 12,
    kVehicleTimeFieldNumber = 9,
    kVehicleAdvisedSpeedFieldNumber = 10,
    kLightTimeFieldNumber = 13,
    kLightAdvisedSpeedFieldNumber = 14,
  };
  // int32 vehicleId = 4;
  void clear_vehicleid();
  int32_t vehicleid() const;
  void set_vehicleid(int32_t value);
  private:
  int32_t _internal_vehicleid() const;
  void _internal_set_vehicleid(int32_t value);
  public:

  // bool b_isValid = 1;
  void clear_b_isvalid();
  bool b_isvalid() const;
  void set_b_isvalid(bool value);
  private:
  bool _internal_b_isvalid() const;
  void _internal_set_b_isvalid(bool value);
  public:

  // bool b_isAlive = 2;
  void clear_b_isalive();
  bool b_isalive() const;
  void set_b_isalive(bool value);
  private:
  bool _internal_b_isalive() const;
  void _internal_set_b_isalive(bool value);
  public:

  // bool b_vehicleValid = 3;
  void clear_b_vehiclevalid();
  bool b_vehiclevalid() const;
  void set_b_vehiclevalid(bool value);
  private:
  bool _internal_b_vehiclevalid() const;
  void _internal_set_b_vehiclevalid(bool value);
  public:

  // bool b_lightValid = 11;
  void clear_b_lightvalid();
  bool b_lightvalid() const;
  void set_b_lightvalid(bool value);
  private:
  bool _internal_b_lightvalid() const;
  void _internal_set_b_lightvalid(bool value);
  public:

  // double vehicleGaussX = 6;
  void clear_vehiclegaussx();
  double vehiclegaussx() const;
  void set_vehiclegaussx(double value);
  private:
  double _internal_vehiclegaussx() const;
  void _internal_set_vehiclegaussx(double value);
  public:

  // double vehicleGaussY = 7;
  void clear_vehiclegaussy();
  double vehiclegaussy() const;
  void set_vehiclegaussy(double value);
  private:
  double _internal_vehiclegaussy() const;
  void _internal_set_vehiclegaussy(double value);
  public:

  // double vehicleSpeed = 8;
  void clear_vehiclespeed();
  double vehiclespeed() const;
  void set_vehiclespeed(double value);
  private:
  double _internal_vehiclespeed() const;
  void _internal_set_vehiclespeed(double value);
  public:

  // int32 vehicleType = 5;
  void clear_vehicletype();
  int32_t vehicletype() const;
  void set_vehicletype(int32_t value);
  private:
  int32_t _internal_vehicletype() const;
  void _internal_set_vehicletype(int32_t value);
  public:

  // int32 lightPhase = 12;
  void clear_lightphase();
  int32_t lightphase() const;
  void set_lightphase(int32_t value);
  private:
  int32_t _internal_lightphase() const;
  void _internal_set_lightphase(int32_t value);
  public:

  // double vehicleTime = 9;
  void clear_vehicletime();
  double vehicletime() const;
  void set_vehicletime(double value);
  private:
  double _internal_vehicletime() const;
  void _internal_set_vehicletime(double value);
  public:

  // double vehicleAdvisedSpeed = 10;
  void clear_vehicleadvisedspeed();
  double vehicleadvisedspeed() const;
  void set_vehicleadvisedspeed(double value);
  private:
  double _internal_vehicleadvisedspeed() const;
  void _internal_set_vehicleadvisedspeed(double value);
  public:

  // double lightTime = 13;
  void clear_lighttime();
  double lighttime() const;
  void set_lighttime(double value);
  private:
  double _internal_lighttime() const;
  void _internal_set_lighttime(double value);
  public:

  // double lightAdvisedSpeed = 14;
  void clear_lightadvisedspeed();
  double lightadvisedspeed() const;
  void set_lightadvisedspeed(double value);
  private:
  double _internal_lightadvisedspeed() const;
  void _internal_set_lightadvisedspeed(double value);
  public:

  // @@protoc_insertion_point(class_scope:ui.Iov)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t vehicleid_;
    bool b_isvalid_;
    bool b_isalive_;
    bool b_vehiclevalid_;
    bool b_lightvalid_;
    double vehiclegaussx_;
    double vehiclegaussy_;
    double vehiclespeed_;
    int32_t vehicletype_;
    int32_t lightphase_;
    double vehicletime_;
    double vehicleadvisedspeed_;
    double lighttime_;
    double lightadvisedspeed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ui_2eproto;
};
// -------------------------------------------------------------------

class Cv final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ui.Cv) */ {
 public:
  inline Cv() : Cv(nullptr) {}
  ~Cv() override;
  explicit PROTOBUF_CONSTEXPR Cv(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Cv(const Cv& from);
  Cv(Cv&& from) noexcept
    : Cv() {
    *this = ::std::move(from);
  }

  inline Cv& operator=(const Cv& from) {
    CopyFrom(from);
    return *this;
  }
  inline Cv& operator=(Cv&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Cv& default_instance() {
    return *internal_default_instance();
  }
  static inline const Cv* internal_default_instance() {
    return reinterpret_cast<const Cv*>(
               &_Cv_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Cv& a, Cv& b) {
    a.Swap(&b);
  }
  inline void Swap(Cv* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Cv* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Cv* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Cv>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Cv& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Cv& from) {
    Cv::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Cv* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ui.Cv";
  }
  protected:
  explicit Cv(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVehicleIdFieldNumber = 4,
    kBIsValidFieldNumber = 1,
    kBIsAliveFieldNumber = 2,
    kBVehicleValidFieldNumber = 3,
    kBLightValidFieldNumber = 11,
    kVehicleGaussXFieldNumber = 6,
    kVehicleGaussYFieldNumber = 7,
    kVehicleSpeedFieldNumber = 8,
    kVehicleTypeFieldNumber = 5,
    kLightPhaseFieldNumber = 12,
    kVehicleTimeFieldNumber = 9,
    kVehicleAdvisedSpeedFieldNumber = 10,
    kLightTimeFieldNumber = 13,
    kLightAdvisedSpeedFieldNumber = 14,
  };
  // int32 vehicleId = 4;
  void clear_vehicleid();
  int32_t vehicleid() const;
  void set_vehicleid(int32_t value);
  private:
  int32_t _internal_vehicleid() const;
  void _internal_set_vehicleid(int32_t value);
  public:

  // bool b_isValid = 1;
  void clear_b_isvalid();
  bool b_isvalid() const;
  void set_b_isvalid(bool value);
  private:
  bool _internal_b_isvalid() const;
  void _internal_set_b_isvalid(bool value);
  public:

  // bool b_isAlive = 2;
  void clear_b_isalive();
  bool b_isalive() const;
  void set_b_isalive(bool value);
  private:
  bool _internal_b_isalive() const;
  void _internal_set_b_isalive(bool value);
  public:

  // bool b_vehicleValid = 3;
  void clear_b_vehiclevalid();
  bool b_vehiclevalid() const;
  void set_b_vehiclevalid(bool value);
  private:
  bool _internal_b_vehiclevalid() const;
  void _internal_set_b_vehiclevalid(bool value);
  public:

  // bool b_lightValid = 11;
  void clear_b_lightvalid();
  bool b_lightvalid() const;
  void set_b_lightvalid(bool value);
  private:
  bool _internal_b_lightvalid() const;
  void _internal_set_b_lightvalid(bool value);
  public:

  // double vehicleGaussX = 6;
  void clear_vehiclegaussx();
  double vehiclegaussx() const;
  void set_vehiclegaussx(double value);
  private:
  double _internal_vehiclegaussx() const;
  void _internal_set_vehiclegaussx(double value);
  public:

  // double vehicleGaussY = 7;
  void clear_vehiclegaussy();
  double vehiclegaussy() const;
  void set_vehiclegaussy(double value);
  private:
  double _internal_vehiclegaussy() const;
  void _internal_set_vehiclegaussy(double value);
  public:

  // double vehicleSpeed = 8;
  void clear_vehiclespeed();
  double vehiclespeed() const;
  void set_vehiclespeed(double value);
  private:
  double _internal_vehiclespeed() const;
  void _internal_set_vehiclespeed(double value);
  public:

  // int32 vehicleType = 5;
  void clear_vehicletype();
  int32_t vehicletype() const;
  void set_vehicletype(int32_t value);
  private:
  int32_t _internal_vehicletype() const;
  void _internal_set_vehicletype(int32_t value);
  public:

  // int32 lightPhase = 12;
  void clear_lightphase();
  int32_t lightphase() const;
  void set_lightphase(int32_t value);
  private:
  int32_t _internal_lightphase() const;
  void _internal_set_lightphase(int32_t value);
  public:

  // double vehicleTime = 9;
  void clear_vehicletime();
  double vehicletime() const;
  void set_vehicletime(double value);
  private:
  double _internal_vehicletime() const;
  void _internal_set_vehicletime(double value);
  public:

  // double vehicleAdvisedSpeed = 10;
  void clear_vehicleadvisedspeed();
  double vehicleadvisedspeed() const;
  void set_vehicleadvisedspeed(double value);
  private:
  double _internal_vehicleadvisedspeed() const;
  void _internal_set_vehicleadvisedspeed(double value);
  public:

  // double lightTime = 13;
  void clear_lighttime();
  double lighttime() const;
  void set_lighttime(double value);
  private:
  double _internal_lighttime() const;
  void _internal_set_lighttime(double value);
  public:

  // double lightAdvisedSpeed = 14;
  void clear_lightadvisedspeed();
  double lightadvisedspeed() const;
  void set_lightadvisedspeed(double value);
  private:
  double _internal_lightadvisedspeed() const;
  void _internal_set_lightadvisedspeed(double value);
  public:

  // @@protoc_insertion_point(class_scope:ui.Cv)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t vehicleid_;
    bool b_isvalid_;
    bool b_isalive_;
    bool b_vehiclevalid_;
    bool b_lightvalid_;
    double vehiclegaussx_;
    double vehiclegaussy_;
    double vehiclespeed_;
    int32_t vehicletype_;
    int32_t lightphase_;
    double vehicletime_;
    double vehicleadvisedspeed_;
    double lighttime_;
    double lightadvisedspeed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ui_2eproto;
};
// -------------------------------------------------------------------

class UiV2PadData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ui.UiV2PadData) */ {
 public:
  inline UiV2PadData() : UiV2PadData(nullptr) {}
  ~UiV2PadData() override;
  explicit PROTOBUF_CONSTEXPR UiV2PadData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UiV2PadData(const UiV2PadData& from);
  UiV2PadData(UiV2PadData&& from) noexcept
    : UiV2PadData() {
    *this = ::std::move(from);
  }

  inline UiV2PadData& operator=(const UiV2PadData& from) {
    CopyFrom(from);
    return *this;
  }
  inline UiV2PadData& operator=(UiV2PadData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UiV2PadData& default_instance() {
    return *internal_default_instance();
  }
  static inline const UiV2PadData* internal_default_instance() {
    return reinterpret_cast<const UiV2PadData*>(
               &_UiV2PadData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(UiV2PadData& a, UiV2PadData& b) {
    a.Swap(&b);
  }
  inline void Swap(UiV2PadData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UiV2PadData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UiV2PadData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UiV2PadData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UiV2PadData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UiV2PadData& from) {
    UiV2PadData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UiV2PadData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ui.UiV2PadData";
  }
  protected:
  explicit UiV2PadData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPostureFieldNumber = 1,
    kIovFieldNumber = 2,
    kCvFieldNumber = 3,
  };
  // repeated .ui.Posture posture = 1;
  int posture_size() const;
  private:
  int _internal_posture_size() const;
  public:
  void clear_posture();
  ::ui::Posture* mutable_posture(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Posture >*
      mutable_posture();
  private:
  const ::ui::Posture& _internal_posture(int index) const;
  ::ui::Posture* _internal_add_posture();
  public:
  const ::ui::Posture& posture(int index) const;
  ::ui::Posture* add_posture();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Posture >&
      posture() const;

  // repeated .ui.Iov iov = 2;
  int iov_size() const;
  private:
  int _internal_iov_size() const;
  public:
  void clear_iov();
  ::ui::Iov* mutable_iov(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Iov >*
      mutable_iov();
  private:
  const ::ui::Iov& _internal_iov(int index) const;
  ::ui::Iov* _internal_add_iov();
  public:
  const ::ui::Iov& iov(int index) const;
  ::ui::Iov* add_iov();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Iov >&
      iov() const;

  // repeated .ui.Cv cv = 3;
  int cv_size() const;
  private:
  int _internal_cv_size() const;
  public:
  void clear_cv();
  ::ui::Cv* mutable_cv(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Cv >*
      mutable_cv();
  private:
  const ::ui::Cv& _internal_cv(int index) const;
  ::ui::Cv* _internal_add_cv();
  public:
  const ::ui::Cv& cv(int index) const;
  ::ui::Cv* add_cv();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Cv >&
      cv() const;

  // @@protoc_insertion_point(class_scope:ui.UiV2PadData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Posture > posture_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Iov > iov_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Cv > cv_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ui_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UiPad2VData

// bool b_stopFlag = 1;
inline void UiPad2VData::clear_b_stopflag() {
  _impl_.b_stopflag_ = false;
}
inline bool UiPad2VData::_internal_b_stopflag() const {
  return _impl_.b_stopflag_;
}
inline bool UiPad2VData::b_stopflag() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_stopFlag)
  return _internal_b_stopflag();
}
inline void UiPad2VData::_internal_set_b_stopflag(bool value) {
  
  _impl_.b_stopflag_ = value;
}
inline void UiPad2VData::set_b_stopflag(bool value) {
  _internal_set_b_stopflag(value);
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_stopFlag)
}

// bool b_speedOff = 2;
inline void UiPad2VData::clear_b_speedoff() {
  _impl_.b_speedoff_ = false;
}
inline bool UiPad2VData::_internal_b_speedoff() const {
  return _impl_.b_speedoff_;
}
inline bool UiPad2VData::b_speedoff() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_speedOff)
  return _internal_b_speedoff();
}
inline void UiPad2VData::_internal_set_b_speedoff(bool value) {
  
  _impl_.b_speedoff_ = value;
}
inline void UiPad2VData::set_b_speedoff(bool value) {
  _internal_set_b_speedoff(value);
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_speedOff)
}

// bool b_steeringOff = 3;
inline void UiPad2VData::clear_b_steeringoff() {
  _impl_.b_steeringoff_ = false;
}
inline bool UiPad2VData::_internal_b_steeringoff() const {
  return _impl_.b_steeringoff_;
}
inline bool UiPad2VData::b_steeringoff() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_steeringOff)
  return _internal_b_steeringoff();
}
inline void UiPad2VData::_internal_set_b_steeringoff(bool value) {
  
  _impl_.b_steeringoff_ = value;
}
inline void UiPad2VData::set_b_steeringoff(bool value) {
  _internal_set_b_steeringoff(value);
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_steeringOff)
}

// bool b_isValid = 4;
inline void UiPad2VData::clear_b_isvalid() {
  _impl_.b_isvalid_ = false;
}
inline bool UiPad2VData::_internal_b_isvalid() const {
  return _impl_.b_isvalid_;
}
inline bool UiPad2VData::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_isValid)
  return _internal_b_isvalid();
}
inline void UiPad2VData::_internal_set_b_isvalid(bool value) {
  
  _impl_.b_isvalid_ = value;
}
inline void UiPad2VData::set_b_isvalid(bool value) {
  _internal_set_b_isvalid(value);
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_isValid)
}

// bool b_config1 = 5;
inline void UiPad2VData::clear_b_config1() {
  _impl_.b_config1_ = false;
}
inline bool UiPad2VData::_internal_b_config1() const {
  return _impl_.b_config1_;
}
inline bool UiPad2VData::b_config1() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_config1)
  return _internal_b_config1();
}
inline void UiPad2VData::_internal_set_b_config1(bool value) {
  
  _impl_.b_config1_ = value;
}
inline void UiPad2VData::set_b_config1(bool value) {
  _internal_set_b_config1(value);
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_config1)
}

// int32 s_targetPath = 6;
inline void UiPad2VData::clear_s_targetpath() {
  _impl_.s_targetpath_ = 0;
}
inline int32_t UiPad2VData::_internal_s_targetpath() const {
  return _impl_.s_targetpath_;
}
inline int32_t UiPad2VData::s_targetpath() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.s_targetPath)
  return _internal_s_targetpath();
}
inline void UiPad2VData::_internal_set_s_targetpath(int32_t value) {
  
  _impl_.s_targetpath_ = value;
}
inline void UiPad2VData::set_s_targetpath(int32_t value) {
  _internal_set_s_targetpath(value);
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.s_targetPath)
}

// bool b_isAlive = 7;
inline void UiPad2VData::clear_b_isalive() {
  _impl_.b_isalive_ = false;
}
inline bool UiPad2VData::_internal_b_isalive() const {
  return _impl_.b_isalive_;
}
inline bool UiPad2VData::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_isAlive)
  return _internal_b_isalive();
}
inline void UiPad2VData::_internal_set_b_isalive(bool value) {
  
  _impl_.b_isalive_ = value;
}
inline void UiPad2VData::set_b_isalive(bool value) {
  _internal_set_b_isalive(value);
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_isAlive)
}

// -------------------------------------------------------------------

// Imu

// double time = 1;
inline void Imu::clear_time() {
  _impl_.time_ = 0;
}
inline double Imu::_internal_time() const {
  return _impl_.time_;
}
inline double Imu::time() const {
  // @@protoc_insertion_point(field_get:ui.Imu.time)
  return _internal_time();
}
inline void Imu::_internal_set_time(double value) {
  
  _impl_.time_ = value;
}
inline void Imu::set_time(double value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:ui.Imu.time)
}

// double velocity = 2;
inline void Imu::clear_velocity() {
  _impl_.velocity_ = 0;
}
inline double Imu::_internal_velocity() const {
  return _impl_.velocity_;
}
inline double Imu::velocity() const {
  // @@protoc_insertion_point(field_get:ui.Imu.velocity)
  return _internal_velocity();
}
inline void Imu::_internal_set_velocity(double value) {
  
  _impl_.velocity_ = value;
}
inline void Imu::set_velocity(double value) {
  _internal_set_velocity(value);
  // @@protoc_insertion_point(field_set:ui.Imu.velocity)
}

// double roll = 3;
inline void Imu::clear_roll() {
  _impl_.roll_ = 0;
}
inline double Imu::_internal_roll() const {
  return _impl_.roll_;
}
inline double Imu::roll() const {
  // @@protoc_insertion_point(field_get:ui.Imu.roll)
  return _internal_roll();
}
inline void Imu::_internal_set_roll(double value) {
  
  _impl_.roll_ = value;
}
inline void Imu::set_roll(double value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:ui.Imu.roll)
}

// double yaw = 4;
inline void Imu::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline double Imu::_internal_yaw() const {
  return _impl_.yaw_;
}
inline double Imu::yaw() const {
  // @@protoc_insertion_point(field_get:ui.Imu.yaw)
  return _internal_yaw();
}
inline void Imu::_internal_set_yaw(double value) {
  
  _impl_.yaw_ = value;
}
inline void Imu::set_yaw(double value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:ui.Imu.yaw)
}

// double pitch = 5;
inline void Imu::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline double Imu::_internal_pitch() const {
  return _impl_.pitch_;
}
inline double Imu::pitch() const {
  // @@protoc_insertion_point(field_get:ui.Imu.pitch)
  return _internal_pitch();
}
inline void Imu::_internal_set_pitch(double value) {
  
  _impl_.pitch_ = value;
}
inline void Imu::set_pitch(double value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:ui.Imu.pitch)
}

// bool b_isValid = 6;
inline void Imu::clear_b_isvalid() {
  _impl_.b_isvalid_ = false;
}
inline bool Imu::_internal_b_isvalid() const {
  return _impl_.b_isvalid_;
}
inline bool Imu::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.Imu.b_isValid)
  return _internal_b_isvalid();
}
inline void Imu::_internal_set_b_isvalid(bool value) {
  
  _impl_.b_isvalid_ = value;
}
inline void Imu::set_b_isvalid(bool value) {
  _internal_set_b_isvalid(value);
  // @@protoc_insertion_point(field_set:ui.Imu.b_isValid)
}

// bool b_gpsValid = 7;
inline void Imu::clear_b_gpsvalid() {
  _impl_.b_gpsvalid_ = false;
}
inline bool Imu::_internal_b_gpsvalid() const {
  return _impl_.b_gpsvalid_;
}
inline bool Imu::b_gpsvalid() const {
  // @@protoc_insertion_point(field_get:ui.Imu.b_gpsValid)
  return _internal_b_gpsvalid();
}
inline void Imu::_internal_set_b_gpsvalid(bool value) {
  
  _impl_.b_gpsvalid_ = value;
}
inline void Imu::set_b_gpsvalid(bool value) {
  _internal_set_b_gpsvalid(value);
  // @@protoc_insertion_point(field_set:ui.Imu.b_gpsValid)
}

// double latitude = 8;
inline void Imu::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline double Imu::_internal_latitude() const {
  return _impl_.latitude_;
}
inline double Imu::latitude() const {
  // @@protoc_insertion_point(field_get:ui.Imu.latitude)
  return _internal_latitude();
}
inline void Imu::_internal_set_latitude(double value) {
  
  _impl_.latitude_ = value;
}
inline void Imu::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:ui.Imu.latitude)
}

// double longitude = 9;
inline void Imu::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline double Imu::_internal_longitude() const {
  return _impl_.longitude_;
}
inline double Imu::longitude() const {
  // @@protoc_insertion_point(field_get:ui.Imu.longitude)
  return _internal_longitude();
}
inline void Imu::_internal_set_longitude(double value) {
  
  _impl_.longitude_ = value;
}
inline void Imu::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:ui.Imu.longitude)
}

// double gaussX = 10;
inline void Imu::clear_gaussx() {
  _impl_.gaussx_ = 0;
}
inline double Imu::_internal_gaussx() const {
  return _impl_.gaussx_;
}
inline double Imu::gaussx() const {
  // @@protoc_insertion_point(field_get:ui.Imu.gaussX)
  return _internal_gaussx();
}
inline void Imu::_internal_set_gaussx(double value) {
  
  _impl_.gaussx_ = value;
}
inline void Imu::set_gaussx(double value) {
  _internal_set_gaussx(value);
  // @@protoc_insertion_point(field_set:ui.Imu.gaussX)
}

// double gaussY = 11;
inline void Imu::clear_gaussy() {
  _impl_.gaussy_ = 0;
}
inline double Imu::_internal_gaussy() const {
  return _impl_.gaussy_;
}
inline double Imu::gaussy() const {
  // @@protoc_insertion_point(field_get:ui.Imu.gaussY)
  return _internal_gaussy();
}
inline void Imu::_internal_set_gaussy(double value) {
  
  _impl_.gaussy_ = value;
}
inline void Imu::set_gaussy(double value) {
  _internal_set_gaussy(value);
  // @@protoc_insertion_point(field_set:ui.Imu.gaussY)
}

// double yawRate = 12;
inline void Imu::clear_yawrate() {
  _impl_.yawrate_ = 0;
}
inline double Imu::_internal_yawrate() const {
  return _impl_.yawrate_;
}
inline double Imu::yawrate() const {
  // @@protoc_insertion_point(field_get:ui.Imu.yawRate)
  return _internal_yawrate();
}
inline void Imu::_internal_set_yawrate(double value) {
  
  _impl_.yawrate_ = value;
}
inline void Imu::set_yawrate(double value) {
  _internal_set_yawrate(value);
  // @@protoc_insertion_point(field_set:ui.Imu.yawRate)
}

// bool b_isAlive = 13;
inline void Imu::clear_b_isalive() {
  _impl_.b_isalive_ = false;
}
inline bool Imu::_internal_b_isalive() const {
  return _impl_.b_isalive_;
}
inline bool Imu::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Imu.b_isAlive)
  return _internal_b_isalive();
}
inline void Imu::_internal_set_b_isalive(bool value) {
  
  _impl_.b_isalive_ = value;
}
inline void Imu::set_b_isalive(bool value) {
  _internal_set_b_isalive(value);
  // @@protoc_insertion_point(field_set:ui.Imu.b_isAlive)
}

// -------------------------------------------------------------------

// Gnss

// double longitude = 1;
inline void Gnss::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline double Gnss::_internal_longitude() const {
  return _impl_.longitude_;
}
inline double Gnss::longitude() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.longitude)
  return _internal_longitude();
}
inline void Gnss::_internal_set_longitude(double value) {
  
  _impl_.longitude_ = value;
}
inline void Gnss::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.longitude)
}

// double latitude = 2;
inline void Gnss::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline double Gnss::_internal_latitude() const {
  return _impl_.latitude_;
}
inline double Gnss::latitude() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.latitude)
  return _internal_latitude();
}
inline void Gnss::_internal_set_latitude(double value) {
  
  _impl_.latitude_ = value;
}
inline void Gnss::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.latitude)
}

// double gaussX = 3;
inline void Gnss::clear_gaussx() {
  _impl_.gaussx_ = 0;
}
inline double Gnss::_internal_gaussx() const {
  return _impl_.gaussx_;
}
inline double Gnss::gaussx() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.gaussX)
  return _internal_gaussx();
}
inline void Gnss::_internal_set_gaussx(double value) {
  
  _impl_.gaussx_ = value;
}
inline void Gnss::set_gaussx(double value) {
  _internal_set_gaussx(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.gaussX)
}

// double gaussY = 4;
inline void Gnss::clear_gaussy() {
  _impl_.gaussy_ = 0;
}
inline double Gnss::_internal_gaussy() const {
  return _impl_.gaussy_;
}
inline double Gnss::gaussy() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.gaussY)
  return _internal_gaussy();
}
inline void Gnss::_internal_set_gaussy(double value) {
  
  _impl_.gaussy_ = value;
}
inline void Gnss::set_gaussy(double value) {
  _internal_set_gaussy(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.gaussY)
}

// double yaw = 5;
inline void Gnss::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline double Gnss::_internal_yaw() const {
  return _impl_.yaw_;
}
inline double Gnss::yaw() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.yaw)
  return _internal_yaw();
}
inline void Gnss::_internal_set_yaw(double value) {
  
  _impl_.yaw_ = value;
}
inline void Gnss::set_yaw(double value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.yaw)
}

// int32 gpsQuality = 6;
inline void Gnss::clear_gpsquality() {
  _impl_.gpsquality_ = 0;
}
inline int32_t Gnss::_internal_gpsquality() const {
  return _impl_.gpsquality_;
}
inline int32_t Gnss::gpsquality() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.gpsQuality)
  return _internal_gpsquality();
}
inline void Gnss::_internal_set_gpsquality(int32_t value) {
  
  _impl_.gpsquality_ = value;
}
inline void Gnss::set_gpsquality(int32_t value) {
  _internal_set_gpsquality(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.gpsQuality)
}

// double utc_second = 7;
inline void Gnss::clear_utc_second() {
  _impl_.utc_second_ = 0;
}
inline double Gnss::_internal_utc_second() const {
  return _impl_.utc_second_;
}
inline double Gnss::utc_second() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.utc_second)
  return _internal_utc_second();
}
inline void Gnss::_internal_set_utc_second(double value) {
  
  _impl_.utc_second_ = value;
}
inline void Gnss::set_utc_second(double value) {
  _internal_set_utc_second(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.utc_second)
}

// bool b_isValid = 8;
inline void Gnss::clear_b_isvalid() {
  _impl_.b_isvalid_ = false;
}
inline bool Gnss::_internal_b_isvalid() const {
  return _impl_.b_isvalid_;
}
inline bool Gnss::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.b_isValid)
  return _internal_b_isvalid();
}
inline void Gnss::_internal_set_b_isvalid(bool value) {
  
  _impl_.b_isvalid_ = value;
}
inline void Gnss::set_b_isvalid(bool value) {
  _internal_set_b_isvalid(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.b_isValid)
}

// bool b_isDiffitial = 9;
inline void Gnss::clear_b_isdiffitial() {
  _impl_.b_isdiffitial_ = false;
}
inline bool Gnss::_internal_b_isdiffitial() const {
  return _impl_.b_isdiffitial_;
}
inline bool Gnss::b_isdiffitial() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.b_isDiffitial)
  return _internal_b_isdiffitial();
}
inline void Gnss::_internal_set_b_isdiffitial(bool value) {
  
  _impl_.b_isdiffitial_ = value;
}
inline void Gnss::set_b_isdiffitial(bool value) {
  _internal_set_b_isdiffitial(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.b_isDiffitial)
}

// bool b_isAlive = 10;
inline void Gnss::clear_b_isalive() {
  _impl_.b_isalive_ = false;
}
inline bool Gnss::_internal_b_isalive() const {
  return _impl_.b_isalive_;
}
inline bool Gnss::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.b_isAlive)
  return _internal_b_isalive();
}
inline void Gnss::_internal_set_b_isalive(bool value) {
  
  _impl_.b_isalive_ = value;
}
inline void Gnss::set_b_isalive(bool value) {
  _internal_set_b_isalive(value);
  // @@protoc_insertion_point(field_set:ui.Gnss.b_isAlive)
}

// -------------------------------------------------------------------

// Posture

// repeated .ui.Imu imu = 1;
inline int Posture::_internal_imu_size() const {
  return _impl_.imu_.size();
}
inline int Posture::imu_size() const {
  return _internal_imu_size();
}
inline void Posture::clear_imu() {
  _impl_.imu_.Clear();
}
inline ::ui::Imu* Posture::mutable_imu(int index) {
  // @@protoc_insertion_point(field_mutable:ui.Posture.imu)
  return _impl_.imu_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Imu >*
Posture::mutable_imu() {
  // @@protoc_insertion_point(field_mutable_list:ui.Posture.imu)
  return &_impl_.imu_;
}
inline const ::ui::Imu& Posture::_internal_imu(int index) const {
  return _impl_.imu_.Get(index);
}
inline const ::ui::Imu& Posture::imu(int index) const {
  // @@protoc_insertion_point(field_get:ui.Posture.imu)
  return _internal_imu(index);
}
inline ::ui::Imu* Posture::_internal_add_imu() {
  return _impl_.imu_.Add();
}
inline ::ui::Imu* Posture::add_imu() {
  ::ui::Imu* _add = _internal_add_imu();
  // @@protoc_insertion_point(field_add:ui.Posture.imu)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Imu >&
Posture::imu() const {
  // @@protoc_insertion_point(field_list:ui.Posture.imu)
  return _impl_.imu_;
}

// repeated .ui.Gnss gnss = 2;
inline int Posture::_internal_gnss_size() const {
  return _impl_.gnss_.size();
}
inline int Posture::gnss_size() const {
  return _internal_gnss_size();
}
inline void Posture::clear_gnss() {
  _impl_.gnss_.Clear();
}
inline ::ui::Gnss* Posture::mutable_gnss(int index) {
  // @@protoc_insertion_point(field_mutable:ui.Posture.gnss)
  return _impl_.gnss_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Gnss >*
Posture::mutable_gnss() {
  // @@protoc_insertion_point(field_mutable_list:ui.Posture.gnss)
  return &_impl_.gnss_;
}
inline const ::ui::Gnss& Posture::_internal_gnss(int index) const {
  return _impl_.gnss_.Get(index);
}
inline const ::ui::Gnss& Posture::gnss(int index) const {
  // @@protoc_insertion_point(field_get:ui.Posture.gnss)
  return _internal_gnss(index);
}
inline ::ui::Gnss* Posture::_internal_add_gnss() {
  return _impl_.gnss_.Add();
}
inline ::ui::Gnss* Posture::add_gnss() {
  ::ui::Gnss* _add = _internal_add_gnss();
  // @@protoc_insertion_point(field_add:ui.Posture.gnss)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Gnss >&
Posture::gnss() const {
  // @@protoc_insertion_point(field_list:ui.Posture.gnss)
  return _impl_.gnss_;
}

// bool b_isAlive = 3;
inline void Posture::clear_b_isalive() {
  _impl_.b_isalive_ = false;
}
inline bool Posture::_internal_b_isalive() const {
  return _impl_.b_isalive_;
}
inline bool Posture::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Posture.b_isAlive)
  return _internal_b_isalive();
}
inline void Posture::_internal_set_b_isalive(bool value) {
  
  _impl_.b_isalive_ = value;
}
inline void Posture::set_b_isalive(bool value) {
  _internal_set_b_isalive(value);
  // @@protoc_insertion_point(field_set:ui.Posture.b_isAlive)
}

// -------------------------------------------------------------------

// Iov

// bool b_isValid = 1;
inline void Iov::clear_b_isvalid() {
  _impl_.b_isvalid_ = false;
}
inline bool Iov::_internal_b_isvalid() const {
  return _impl_.b_isvalid_;
}
inline bool Iov::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.Iov.b_isValid)
  return _internal_b_isvalid();
}
inline void Iov::_internal_set_b_isvalid(bool value) {
  
  _impl_.b_isvalid_ = value;
}
inline void Iov::set_b_isvalid(bool value) {
  _internal_set_b_isvalid(value);
  // @@protoc_insertion_point(field_set:ui.Iov.b_isValid)
}

// bool b_isAlive = 2;
inline void Iov::clear_b_isalive() {
  _impl_.b_isalive_ = false;
}
inline bool Iov::_internal_b_isalive() const {
  return _impl_.b_isalive_;
}
inline bool Iov::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Iov.b_isAlive)
  return _internal_b_isalive();
}
inline void Iov::_internal_set_b_isalive(bool value) {
  
  _impl_.b_isalive_ = value;
}
inline void Iov::set_b_isalive(bool value) {
  _internal_set_b_isalive(value);
  // @@protoc_insertion_point(field_set:ui.Iov.b_isAlive)
}

// bool b_vehicleValid = 3;
inline void Iov::clear_b_vehiclevalid() {
  _impl_.b_vehiclevalid_ = false;
}
inline bool Iov::_internal_b_vehiclevalid() const {
  return _impl_.b_vehiclevalid_;
}
inline bool Iov::b_vehiclevalid() const {
  // @@protoc_insertion_point(field_get:ui.Iov.b_vehicleValid)
  return _internal_b_vehiclevalid();
}
inline void Iov::_internal_set_b_vehiclevalid(bool value) {
  
  _impl_.b_vehiclevalid_ = value;
}
inline void Iov::set_b_vehiclevalid(bool value) {
  _internal_set_b_vehiclevalid(value);
  // @@protoc_insertion_point(field_set:ui.Iov.b_vehicleValid)
}

// int32 vehicleId = 4;
inline void Iov::clear_vehicleid() {
  _impl_.vehicleid_ = 0;
}
inline int32_t Iov::_internal_vehicleid() const {
  return _impl_.vehicleid_;
}
inline int32_t Iov::vehicleid() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleId)
  return _internal_vehicleid();
}
inline void Iov::_internal_set_vehicleid(int32_t value) {
  
  _impl_.vehicleid_ = value;
}
inline void Iov::set_vehicleid(int32_t value) {
  _internal_set_vehicleid(value);
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleId)
}

// int32 vehicleType = 5;
inline void Iov::clear_vehicletype() {
  _impl_.vehicletype_ = 0;
}
inline int32_t Iov::_internal_vehicletype() const {
  return _impl_.vehicletype_;
}
inline int32_t Iov::vehicletype() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleType)
  return _internal_vehicletype();
}
inline void Iov::_internal_set_vehicletype(int32_t value) {
  
  _impl_.vehicletype_ = value;
}
inline void Iov::set_vehicletype(int32_t value) {
  _internal_set_vehicletype(value);
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleType)
}

// double vehicleGaussX = 6;
inline void Iov::clear_vehiclegaussx() {
  _impl_.vehiclegaussx_ = 0;
}
inline double Iov::_internal_vehiclegaussx() const {
  return _impl_.vehiclegaussx_;
}
inline double Iov::vehiclegaussx() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleGaussX)
  return _internal_vehiclegaussx();
}
inline void Iov::_internal_set_vehiclegaussx(double value) {
  
  _impl_.vehiclegaussx_ = value;
}
inline void Iov::set_vehiclegaussx(double value) {
  _internal_set_vehiclegaussx(value);
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleGaussX)
}

// double vehicleGaussY = 7;
inline void Iov::clear_vehiclegaussy() {
  _impl_.vehiclegaussy_ = 0;
}
inline double Iov::_internal_vehiclegaussy() const {
  return _impl_.vehiclegaussy_;
}
inline double Iov::vehiclegaussy() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleGaussY)
  return _internal_vehiclegaussy();
}
inline void Iov::_internal_set_vehiclegaussy(double value) {
  
  _impl_.vehiclegaussy_ = value;
}
inline void Iov::set_vehiclegaussy(double value) {
  _internal_set_vehiclegaussy(value);
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleGaussY)
}

// double vehicleSpeed = 8;
inline void Iov::clear_vehiclespeed() {
  _impl_.vehiclespeed_ = 0;
}
inline double Iov::_internal_vehiclespeed() const {
  return _impl_.vehiclespeed_;
}
inline double Iov::vehiclespeed() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleSpeed)
  return _internal_vehiclespeed();
}
inline void Iov::_internal_set_vehiclespeed(double value) {
  
  _impl_.vehiclespeed_ = value;
}
inline void Iov::set_vehiclespeed(double value) {
  _internal_set_vehiclespeed(value);
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleSpeed)
}

// double vehicleTime = 9;
inline void Iov::clear_vehicletime() {
  _impl_.vehicletime_ = 0;
}
inline double Iov::_internal_vehicletime() const {
  return _impl_.vehicletime_;
}
inline double Iov::vehicletime() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleTime)
  return _internal_vehicletime();
}
inline void Iov::_internal_set_vehicletime(double value) {
  
  _impl_.vehicletime_ = value;
}
inline void Iov::set_vehicletime(double value) {
  _internal_set_vehicletime(value);
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleTime)
}

// double vehicleAdvisedSpeed = 10;
inline void Iov::clear_vehicleadvisedspeed() {
  _impl_.vehicleadvisedspeed_ = 0;
}
inline double Iov::_internal_vehicleadvisedspeed() const {
  return _impl_.vehicleadvisedspeed_;
}
inline double Iov::vehicleadvisedspeed() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleAdvisedSpeed)
  return _internal_vehicleadvisedspeed();
}
inline void Iov::_internal_set_vehicleadvisedspeed(double value) {
  
  _impl_.vehicleadvisedspeed_ = value;
}
inline void Iov::set_vehicleadvisedspeed(double value) {
  _internal_set_vehicleadvisedspeed(value);
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleAdvisedSpeed)
}

// bool b_lightValid = 11;
inline void Iov::clear_b_lightvalid() {
  _impl_.b_lightvalid_ = false;
}
inline bool Iov::_internal_b_lightvalid() const {
  return _impl_.b_lightvalid_;
}
inline bool Iov::b_lightvalid() const {
  // @@protoc_insertion_point(field_get:ui.Iov.b_lightValid)
  return _internal_b_lightvalid();
}
inline void Iov::_internal_set_b_lightvalid(bool value) {
  
  _impl_.b_lightvalid_ = value;
}
inline void Iov::set_b_lightvalid(bool value) {
  _internal_set_b_lightvalid(value);
  // @@protoc_insertion_point(field_set:ui.Iov.b_lightValid)
}

// int32 lightPhase = 12;
inline void Iov::clear_lightphase() {
  _impl_.lightphase_ = 0;
}
inline int32_t Iov::_internal_lightphase() const {
  return _impl_.lightphase_;
}
inline int32_t Iov::lightphase() const {
  // @@protoc_insertion_point(field_get:ui.Iov.lightPhase)
  return _internal_lightphase();
}
inline void Iov::_internal_set_lightphase(int32_t value) {
  
  _impl_.lightphase_ = value;
}
inline void Iov::set_lightphase(int32_t value) {
  _internal_set_lightphase(value);
  // @@protoc_insertion_point(field_set:ui.Iov.lightPhase)
}

// double lightTime = 13;
inline void Iov::clear_lighttime() {
  _impl_.lighttime_ = 0;
}
inline double Iov::_internal_lighttime() const {
  return _impl_.lighttime_;
}
inline double Iov::lighttime() const {
  // @@protoc_insertion_point(field_get:ui.Iov.lightTime)
  return _internal_lighttime();
}
inline void Iov::_internal_set_lighttime(double value) {
  
  _impl_.lighttime_ = value;
}
inline void Iov::set_lighttime(double value) {
  _internal_set_lighttime(value);
  // @@protoc_insertion_point(field_set:ui.Iov.lightTime)
}

// double lightAdvisedSpeed = 14;
inline void Iov::clear_lightadvisedspeed() {
  _impl_.lightadvisedspeed_ = 0;
}
inline double Iov::_internal_lightadvisedspeed() const {
  return _impl_.lightadvisedspeed_;
}
inline double Iov::lightadvisedspeed() const {
  // @@protoc_insertion_point(field_get:ui.Iov.lightAdvisedSpeed)
  return _internal_lightadvisedspeed();
}
inline void Iov::_internal_set_lightadvisedspeed(double value) {
  
  _impl_.lightadvisedspeed_ = value;
}
inline void Iov::set_lightadvisedspeed(double value) {
  _internal_set_lightadvisedspeed(value);
  // @@protoc_insertion_point(field_set:ui.Iov.lightAdvisedSpeed)
}

// -------------------------------------------------------------------

// Cv

// bool b_isValid = 1;
inline void Cv::clear_b_isvalid() {
  _impl_.b_isvalid_ = false;
}
inline bool Cv::_internal_b_isvalid() const {
  return _impl_.b_isvalid_;
}
inline bool Cv::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.Cv.b_isValid)
  return _internal_b_isvalid();
}
inline void Cv::_internal_set_b_isvalid(bool value) {
  
  _impl_.b_isvalid_ = value;
}
inline void Cv::set_b_isvalid(bool value) {
  _internal_set_b_isvalid(value);
  // @@protoc_insertion_point(field_set:ui.Cv.b_isValid)
}

// bool b_isAlive = 2;
inline void Cv::clear_b_isalive() {
  _impl_.b_isalive_ = false;
}
inline bool Cv::_internal_b_isalive() const {
  return _impl_.b_isalive_;
}
inline bool Cv::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Cv.b_isAlive)
  return _internal_b_isalive();
}
inline void Cv::_internal_set_b_isalive(bool value) {
  
  _impl_.b_isalive_ = value;
}
inline void Cv::set_b_isalive(bool value) {
  _internal_set_b_isalive(value);
  // @@protoc_insertion_point(field_set:ui.Cv.b_isAlive)
}

// bool b_vehicleValid = 3;
inline void Cv::clear_b_vehiclevalid() {
  _impl_.b_vehiclevalid_ = false;
}
inline bool Cv::_internal_b_vehiclevalid() const {
  return _impl_.b_vehiclevalid_;
}
inline bool Cv::b_vehiclevalid() const {
  // @@protoc_insertion_point(field_get:ui.Cv.b_vehicleValid)
  return _internal_b_vehiclevalid();
}
inline void Cv::_internal_set_b_vehiclevalid(bool value) {
  
  _impl_.b_vehiclevalid_ = value;
}
inline void Cv::set_b_vehiclevalid(bool value) {
  _internal_set_b_vehiclevalid(value);
  // @@protoc_insertion_point(field_set:ui.Cv.b_vehicleValid)
}

// int32 vehicleId = 4;
inline void Cv::clear_vehicleid() {
  _impl_.vehicleid_ = 0;
}
inline int32_t Cv::_internal_vehicleid() const {
  return _impl_.vehicleid_;
}
inline int32_t Cv::vehicleid() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleId)
  return _internal_vehicleid();
}
inline void Cv::_internal_set_vehicleid(int32_t value) {
  
  _impl_.vehicleid_ = value;
}
inline void Cv::set_vehicleid(int32_t value) {
  _internal_set_vehicleid(value);
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleId)
}

// int32 vehicleType = 5;
inline void Cv::clear_vehicletype() {
  _impl_.vehicletype_ = 0;
}
inline int32_t Cv::_internal_vehicletype() const {
  return _impl_.vehicletype_;
}
inline int32_t Cv::vehicletype() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleType)
  return _internal_vehicletype();
}
inline void Cv::_internal_set_vehicletype(int32_t value) {
  
  _impl_.vehicletype_ = value;
}
inline void Cv::set_vehicletype(int32_t value) {
  _internal_set_vehicletype(value);
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleType)
}

// double vehicleGaussX = 6;
inline void Cv::clear_vehiclegaussx() {
  _impl_.vehiclegaussx_ = 0;
}
inline double Cv::_internal_vehiclegaussx() const {
  return _impl_.vehiclegaussx_;
}
inline double Cv::vehiclegaussx() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleGaussX)
  return _internal_vehiclegaussx();
}
inline void Cv::_internal_set_vehiclegaussx(double value) {
  
  _impl_.vehiclegaussx_ = value;
}
inline void Cv::set_vehiclegaussx(double value) {
  _internal_set_vehiclegaussx(value);
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleGaussX)
}

// double vehicleGaussY = 7;
inline void Cv::clear_vehiclegaussy() {
  _impl_.vehiclegaussy_ = 0;
}
inline double Cv::_internal_vehiclegaussy() const {
  return _impl_.vehiclegaussy_;
}
inline double Cv::vehiclegaussy() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleGaussY)
  return _internal_vehiclegaussy();
}
inline void Cv::_internal_set_vehiclegaussy(double value) {
  
  _impl_.vehiclegaussy_ = value;
}
inline void Cv::set_vehiclegaussy(double value) {
  _internal_set_vehiclegaussy(value);
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleGaussY)
}

// double vehicleSpeed = 8;
inline void Cv::clear_vehiclespeed() {
  _impl_.vehiclespeed_ = 0;
}
inline double Cv::_internal_vehiclespeed() const {
  return _impl_.vehiclespeed_;
}
inline double Cv::vehiclespeed() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleSpeed)
  return _internal_vehiclespeed();
}
inline void Cv::_internal_set_vehiclespeed(double value) {
  
  _impl_.vehiclespeed_ = value;
}
inline void Cv::set_vehiclespeed(double value) {
  _internal_set_vehiclespeed(value);
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleSpeed)
}

// double vehicleTime = 9;
inline void Cv::clear_vehicletime() {
  _impl_.vehicletime_ = 0;
}
inline double Cv::_internal_vehicletime() const {
  return _impl_.vehicletime_;
}
inline double Cv::vehicletime() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleTime)
  return _internal_vehicletime();
}
inline void Cv::_internal_set_vehicletime(double value) {
  
  _impl_.vehicletime_ = value;
}
inline void Cv::set_vehicletime(double value) {
  _internal_set_vehicletime(value);
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleTime)
}

// double vehicleAdvisedSpeed = 10;
inline void Cv::clear_vehicleadvisedspeed() {
  _impl_.vehicleadvisedspeed_ = 0;
}
inline double Cv::_internal_vehicleadvisedspeed() const {
  return _impl_.vehicleadvisedspeed_;
}
inline double Cv::vehicleadvisedspeed() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleAdvisedSpeed)
  return _internal_vehicleadvisedspeed();
}
inline void Cv::_internal_set_vehicleadvisedspeed(double value) {
  
  _impl_.vehicleadvisedspeed_ = value;
}
inline void Cv::set_vehicleadvisedspeed(double value) {
  _internal_set_vehicleadvisedspeed(value);
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleAdvisedSpeed)
}

// bool b_lightValid = 11;
inline void Cv::clear_b_lightvalid() {
  _impl_.b_lightvalid_ = false;
}
inline bool Cv::_internal_b_lightvalid() const {
  return _impl_.b_lightvalid_;
}
inline bool Cv::b_lightvalid() const {
  // @@protoc_insertion_point(field_get:ui.Cv.b_lightValid)
  return _internal_b_lightvalid();
}
inline void Cv::_internal_set_b_lightvalid(bool value) {
  
  _impl_.b_lightvalid_ = value;
}
inline void Cv::set_b_lightvalid(bool value) {
  _internal_set_b_lightvalid(value);
  // @@protoc_insertion_point(field_set:ui.Cv.b_lightValid)
}

// int32 lightPhase = 12;
inline void Cv::clear_lightphase() {
  _impl_.lightphase_ = 0;
}
inline int32_t Cv::_internal_lightphase() const {
  return _impl_.lightphase_;
}
inline int32_t Cv::lightphase() const {
  // @@protoc_insertion_point(field_get:ui.Cv.lightPhase)
  return _internal_lightphase();
}
inline void Cv::_internal_set_lightphase(int32_t value) {
  
  _impl_.lightphase_ = value;
}
inline void Cv::set_lightphase(int32_t value) {
  _internal_set_lightphase(value);
  // @@protoc_insertion_point(field_set:ui.Cv.lightPhase)
}

// double lightTime = 13;
inline void Cv::clear_lighttime() {
  _impl_.lighttime_ = 0;
}
inline double Cv::_internal_lighttime() const {
  return _impl_.lighttime_;
}
inline double Cv::lighttime() const {
  // @@protoc_insertion_point(field_get:ui.Cv.lightTime)
  return _internal_lighttime();
}
inline void Cv::_internal_set_lighttime(double value) {
  
  _impl_.lighttime_ = value;
}
inline void Cv::set_lighttime(double value) {
  _internal_set_lighttime(value);
  // @@protoc_insertion_point(field_set:ui.Cv.lightTime)
}

// double lightAdvisedSpeed = 14;
inline void Cv::clear_lightadvisedspeed() {
  _impl_.lightadvisedspeed_ = 0;
}
inline double Cv::_internal_lightadvisedspeed() const {
  return _impl_.lightadvisedspeed_;
}
inline double Cv::lightadvisedspeed() const {
  // @@protoc_insertion_point(field_get:ui.Cv.lightAdvisedSpeed)
  return _internal_lightadvisedspeed();
}
inline void Cv::_internal_set_lightadvisedspeed(double value) {
  
  _impl_.lightadvisedspeed_ = value;
}
inline void Cv::set_lightadvisedspeed(double value) {
  _internal_set_lightadvisedspeed(value);
  // @@protoc_insertion_point(field_set:ui.Cv.lightAdvisedSpeed)
}

// -------------------------------------------------------------------

// UiV2PadData

// repeated .ui.Posture posture = 1;
inline int UiV2PadData::_internal_posture_size() const {
  return _impl_.posture_.size();
}
inline int UiV2PadData::posture_size() const {
  return _internal_posture_size();
}
inline void UiV2PadData::clear_posture() {
  _impl_.posture_.Clear();
}
inline ::ui::Posture* UiV2PadData::mutable_posture(int index) {
  // @@protoc_insertion_point(field_mutable:ui.UiV2PadData.posture)
  return _impl_.posture_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Posture >*
UiV2PadData::mutable_posture() {
  // @@protoc_insertion_point(field_mutable_list:ui.UiV2PadData.posture)
  return &_impl_.posture_;
}
inline const ::ui::Posture& UiV2PadData::_internal_posture(int index) const {
  return _impl_.posture_.Get(index);
}
inline const ::ui::Posture& UiV2PadData::posture(int index) const {
  // @@protoc_insertion_point(field_get:ui.UiV2PadData.posture)
  return _internal_posture(index);
}
inline ::ui::Posture* UiV2PadData::_internal_add_posture() {
  return _impl_.posture_.Add();
}
inline ::ui::Posture* UiV2PadData::add_posture() {
  ::ui::Posture* _add = _internal_add_posture();
  // @@protoc_insertion_point(field_add:ui.UiV2PadData.posture)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Posture >&
UiV2PadData::posture() const {
  // @@protoc_insertion_point(field_list:ui.UiV2PadData.posture)
  return _impl_.posture_;
}

// repeated .ui.Iov iov = 2;
inline int UiV2PadData::_internal_iov_size() const {
  return _impl_.iov_.size();
}
inline int UiV2PadData::iov_size() const {
  return _internal_iov_size();
}
inline void UiV2PadData::clear_iov() {
  _impl_.iov_.Clear();
}
inline ::ui::Iov* UiV2PadData::mutable_iov(int index) {
  // @@protoc_insertion_point(field_mutable:ui.UiV2PadData.iov)
  return _impl_.iov_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Iov >*
UiV2PadData::mutable_iov() {
  // @@protoc_insertion_point(field_mutable_list:ui.UiV2PadData.iov)
  return &_impl_.iov_;
}
inline const ::ui::Iov& UiV2PadData::_internal_iov(int index) const {
  return _impl_.iov_.Get(index);
}
inline const ::ui::Iov& UiV2PadData::iov(int index) const {
  // @@protoc_insertion_point(field_get:ui.UiV2PadData.iov)
  return _internal_iov(index);
}
inline ::ui::Iov* UiV2PadData::_internal_add_iov() {
  return _impl_.iov_.Add();
}
inline ::ui::Iov* UiV2PadData::add_iov() {
  ::ui::Iov* _add = _internal_add_iov();
  // @@protoc_insertion_point(field_add:ui.UiV2PadData.iov)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Iov >&
UiV2PadData::iov() const {
  // @@protoc_insertion_point(field_list:ui.UiV2PadData.iov)
  return _impl_.iov_;
}

// repeated .ui.Cv cv = 3;
inline int UiV2PadData::_internal_cv_size() const {
  return _impl_.cv_.size();
}
inline int UiV2PadData::cv_size() const {
  return _internal_cv_size();
}
inline void UiV2PadData::clear_cv() {
  _impl_.cv_.Clear();
}
inline ::ui::Cv* UiV2PadData::mutable_cv(int index) {
  // @@protoc_insertion_point(field_mutable:ui.UiV2PadData.cv)
  return _impl_.cv_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Cv >*
UiV2PadData::mutable_cv() {
  // @@protoc_insertion_point(field_mutable_list:ui.UiV2PadData.cv)
  return &_impl_.cv_;
}
inline const ::ui::Cv& UiV2PadData::_internal_cv(int index) const {
  return _impl_.cv_.Get(index);
}
inline const ::ui::Cv& UiV2PadData::cv(int index) const {
  // @@protoc_insertion_point(field_get:ui.UiV2PadData.cv)
  return _internal_cv(index);
}
inline ::ui::Cv* UiV2PadData::_internal_add_cv() {
  return _impl_.cv_.Add();
}
inline ::ui::Cv* UiV2PadData::add_cv() {
  ::ui::Cv* _add = _internal_add_cv();
  // @@protoc_insertion_point(field_add:ui.UiV2PadData.cv)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ui::Cv >&
UiV2PadData::cv() const {
  // @@protoc_insertion_point(field_list:ui.UiV2PadData.cv)
  return _impl_.cv_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ui

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ui_2eproto
