// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg2vehicle.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg2vehicle_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg2vehicle_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "objects.pb.h"
#include "decision.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg2vehicle_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg2vehicle_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg2vehicle_2eproto;
namespace infopack {
class DecisionsListProto;
struct DecisionsListProtoDefaultTypeInternal;
extern DecisionsListProtoDefaultTypeInternal _DecisionsListProto_default_instance_;
}  // namespace infopack
PROTOBUF_NAMESPACE_OPEN
template<> ::infopack::DecisionsListProto* Arena::CreateMaybeMessage<::infopack::DecisionsListProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace infopack {

// ===================================================================

class DecisionsListProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:infopack.DecisionsListProto) */ {
 public:
  inline DecisionsListProto() : DecisionsListProto(nullptr) {}
  ~DecisionsListProto() override;
  explicit PROTOBUF_CONSTEXPR DecisionsListProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DecisionsListProto(const DecisionsListProto& from);
  DecisionsListProto(DecisionsListProto&& from) noexcept
    : DecisionsListProto() {
    *this = ::std::move(from);
  }

  inline DecisionsListProto& operator=(const DecisionsListProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline DecisionsListProto& operator=(DecisionsListProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DecisionsListProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const DecisionsListProto* internal_default_instance() {
    return reinterpret_cast<const DecisionsListProto*>(
               &_DecisionsListProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DecisionsListProto& a, DecisionsListProto& b) {
    a.Swap(&b);
  }
  inline void Swap(DecisionsListProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DecisionsListProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DecisionsListProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DecisionsListProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DecisionsListProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DecisionsListProto& from) {
    DecisionsListProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DecisionsListProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "infopack.DecisionsListProto";
  }
  protected:
  explicit DecisionsListProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDispatchFieldNumber = 1,
    kObjectsFieldNumber = 2,
  };
  // repeated .infopack.DispatchProto dispatch = 1;
  int dispatch_size() const;
  private:
  int _internal_dispatch_size() const;
  public:
  void clear_dispatch();
  ::infopack::DispatchProto* mutable_dispatch(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::DispatchProto >*
      mutable_dispatch();
  private:
  const ::infopack::DispatchProto& _internal_dispatch(int index) const;
  ::infopack::DispatchProto* _internal_add_dispatch();
  public:
  const ::infopack::DispatchProto& dispatch(int index) const;
  ::infopack::DispatchProto* add_dispatch();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::DispatchProto >&
      dispatch() const;

  // repeated .infopack.ObjectsProto objects = 2;
  int objects_size() const;
  private:
  int _internal_objects_size() const;
  public:
  void clear_objects();
  ::infopack::ObjectsProto* mutable_objects(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::ObjectsProto >*
      mutable_objects();
  private:
  const ::infopack::ObjectsProto& _internal_objects(int index) const;
  ::infopack::ObjectsProto* _internal_add_objects();
  public:
  const ::infopack::ObjectsProto& objects(int index) const;
  ::infopack::ObjectsProto* add_objects();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::ObjectsProto >&
      objects() const;

  // @@protoc_insertion_point(class_scope:infopack.DecisionsListProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::DispatchProto > dispatch_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::ObjectsProto > objects_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg2vehicle_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DecisionsListProto

// repeated .infopack.DispatchProto dispatch = 1;
inline int DecisionsListProto::_internal_dispatch_size() const {
  return _impl_.dispatch_.size();
}
inline int DecisionsListProto::dispatch_size() const {
  return _internal_dispatch_size();
}
inline ::infopack::DispatchProto* DecisionsListProto::mutable_dispatch(int index) {
  // @@protoc_insertion_point(field_mutable:infopack.DecisionsListProto.dispatch)
  return _impl_.dispatch_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::DispatchProto >*
DecisionsListProto::mutable_dispatch() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DecisionsListProto.dispatch)
  return &_impl_.dispatch_;
}
inline const ::infopack::DispatchProto& DecisionsListProto::_internal_dispatch(int index) const {
  return _impl_.dispatch_.Get(index);
}
inline const ::infopack::DispatchProto& DecisionsListProto::dispatch(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DecisionsListProto.dispatch)
  return _internal_dispatch(index);
}
inline ::infopack::DispatchProto* DecisionsListProto::_internal_add_dispatch() {
  return _impl_.dispatch_.Add();
}
inline ::infopack::DispatchProto* DecisionsListProto::add_dispatch() {
  ::infopack::DispatchProto* _add = _internal_add_dispatch();
  // @@protoc_insertion_point(field_add:infopack.DecisionsListProto.dispatch)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::DispatchProto >&
DecisionsListProto::dispatch() const {
  // @@protoc_insertion_point(field_list:infopack.DecisionsListProto.dispatch)
  return _impl_.dispatch_;
}

// repeated .infopack.ObjectsProto objects = 2;
inline int DecisionsListProto::_internal_objects_size() const {
  return _impl_.objects_.size();
}
inline int DecisionsListProto::objects_size() const {
  return _internal_objects_size();
}
inline ::infopack::ObjectsProto* DecisionsListProto::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:infopack.DecisionsListProto.objects)
  return _impl_.objects_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::ObjectsProto >*
DecisionsListProto::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DecisionsListProto.objects)
  return &_impl_.objects_;
}
inline const ::infopack::ObjectsProto& DecisionsListProto::_internal_objects(int index) const {
  return _impl_.objects_.Get(index);
}
inline const ::infopack::ObjectsProto& DecisionsListProto::objects(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DecisionsListProto.objects)
  return _internal_objects(index);
}
inline ::infopack::ObjectsProto* DecisionsListProto::_internal_add_objects() {
  return _impl_.objects_.Add();
}
inline ::infopack::ObjectsProto* DecisionsListProto::add_objects() {
  ::infopack::ObjectsProto* _add = _internal_add_objects();
  // @@protoc_insertion_point(field_add:infopack.DecisionsListProto.objects)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::infopack::ObjectsProto >&
DecisionsListProto::objects() const {
  // @@protoc_insertion_point(field_list:infopack.DecisionsListProto.objects)
  return _impl_.objects_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg2vehicle_2eproto
