// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic_light.proto

#include "traffic_light.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace infopack {
PROTOBUF_CONSTEXPR TrafficLight::TrafficLight(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.active_)*/false
  , /*decltype(_impl_.state_)*/0
  , /*decltype(_impl_.remaining_time_)*/0
  , /*decltype(_impl_.lane_length_before_intersection_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TrafficLightDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrafficLightDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrafficLightDefaultTypeInternal() {}
  union {
    TrafficLight _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrafficLightDefaultTypeInternal _TrafficLight_default_instance_;
}  // namespace infopack
static ::_pb::Metadata file_level_metadata_traffic_5flight_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_traffic_5flight_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_traffic_5flight_2eproto = nullptr;

const uint32_t TableStruct_traffic_5flight_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::infopack::TrafficLight, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::infopack::TrafficLight, _impl_.active_),
  PROTOBUF_FIELD_OFFSET(::infopack::TrafficLight, _impl_.state_),
  PROTOBUF_FIELD_OFFSET(::infopack::TrafficLight, _impl_.remaining_time_),
  PROTOBUF_FIELD_OFFSET(::infopack::TrafficLight, _impl_.lane_length_before_intersection_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::infopack::TrafficLight)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::infopack::_TrafficLight_default_instance_._instance,
};

const char descriptor_table_protodef_traffic_5flight_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023traffic_light.proto\022\010infopack\"\307\001\n\014Traf"
  "ficLight\022\016\n\006active\030\001 \001(\010\022+\n\005state\030\002 \001(\0162"
  "\034.infopack.TrafficLight.State\022\026\n\016remaini"
  "ng_time\030\003 \001(\001\022\'\n\037lane_length_before_inte"
  "rsection\030\004 \001(\001\"9\n\005State\022\r\n\tRED_LIGHT\020\000\022\020"
  "\n\014YELLOW_LIGHT\020\001\022\017\n\013GREEN_LIGHT\020\002b\006proto"
  "3"
  ;
static ::_pbi::once_flag descriptor_table_traffic_5flight_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_traffic_5flight_2eproto = {
    false, false, 241, descriptor_table_protodef_traffic_5flight_2eproto,
    "traffic_light.proto",
    &descriptor_table_traffic_5flight_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_traffic_5flight_2eproto::offsets,
    file_level_metadata_traffic_5flight_2eproto, file_level_enum_descriptors_traffic_5flight_2eproto,
    file_level_service_descriptors_traffic_5flight_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_traffic_5flight_2eproto_getter() {
  return &descriptor_table_traffic_5flight_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_traffic_5flight_2eproto(&descriptor_table_traffic_5flight_2eproto);
namespace infopack {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TrafficLight_State_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_traffic_5flight_2eproto);
  return file_level_enum_descriptors_traffic_5flight_2eproto[0];
}
bool TrafficLight_State_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr TrafficLight_State TrafficLight::RED_LIGHT;
constexpr TrafficLight_State TrafficLight::YELLOW_LIGHT;
constexpr TrafficLight_State TrafficLight::GREEN_LIGHT;
constexpr TrafficLight_State TrafficLight::State_MIN;
constexpr TrafficLight_State TrafficLight::State_MAX;
constexpr int TrafficLight::State_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class TrafficLight::_Internal {
 public:
};

TrafficLight::TrafficLight(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:infopack.TrafficLight)
}
TrafficLight::TrafficLight(const TrafficLight& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TrafficLight* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.active_){}
    , decltype(_impl_.state_){}
    , decltype(_impl_.remaining_time_){}
    , decltype(_impl_.lane_length_before_intersection_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.active_, &from._impl_.active_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.lane_length_before_intersection_) -
    reinterpret_cast<char*>(&_impl_.active_)) + sizeof(_impl_.lane_length_before_intersection_));
  // @@protoc_insertion_point(copy_constructor:infopack.TrafficLight)
}

inline void TrafficLight::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.active_){false}
    , decltype(_impl_.state_){0}
    , decltype(_impl_.remaining_time_){0}
    , decltype(_impl_.lane_length_before_intersection_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TrafficLight::~TrafficLight() {
  // @@protoc_insertion_point(destructor:infopack.TrafficLight)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TrafficLight::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TrafficLight::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TrafficLight::Clear() {
// @@protoc_insertion_point(message_clear_start:infopack.TrafficLight)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.active_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.lane_length_before_intersection_) -
      reinterpret_cast<char*>(&_impl_.active_)) + sizeof(_impl_.lane_length_before_intersection_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TrafficLight::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool active = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.active_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .infopack.TrafficLight.State state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_state(static_cast<::infopack::TrafficLight_State>(val));
        } else
          goto handle_unusual;
        continue;
      // double remaining_time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.remaining_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double lane_length_before_intersection = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.lane_length_before_intersection_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TrafficLight::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:infopack.TrafficLight)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool active = 1;
  if (this->_internal_active() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_active(), target);
  }

  // .infopack.TrafficLight.State state = 2;
  if (this->_internal_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_state(), target);
  }

  // double remaining_time = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_remaining_time = this->_internal_remaining_time();
  uint64_t raw_remaining_time;
  memcpy(&raw_remaining_time, &tmp_remaining_time, sizeof(tmp_remaining_time));
  if (raw_remaining_time != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_remaining_time(), target);
  }

  // double lane_length_before_intersection = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_lane_length_before_intersection = this->_internal_lane_length_before_intersection();
  uint64_t raw_lane_length_before_intersection;
  memcpy(&raw_lane_length_before_intersection, &tmp_lane_length_before_intersection, sizeof(tmp_lane_length_before_intersection));
  if (raw_lane_length_before_intersection != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_lane_length_before_intersection(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:infopack.TrafficLight)
  return target;
}

size_t TrafficLight::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:infopack.TrafficLight)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool active = 1;
  if (this->_internal_active() != 0) {
    total_size += 1 + 1;
  }

  // .infopack.TrafficLight.State state = 2;
  if (this->_internal_state() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_state());
  }

  // double remaining_time = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_remaining_time = this->_internal_remaining_time();
  uint64_t raw_remaining_time;
  memcpy(&raw_remaining_time, &tmp_remaining_time, sizeof(tmp_remaining_time));
  if (raw_remaining_time != 0) {
    total_size += 1 + 8;
  }

  // double lane_length_before_intersection = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_lane_length_before_intersection = this->_internal_lane_length_before_intersection();
  uint64_t raw_lane_length_before_intersection;
  memcpy(&raw_lane_length_before_intersection, &tmp_lane_length_before_intersection, sizeof(tmp_lane_length_before_intersection));
  if (raw_lane_length_before_intersection != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TrafficLight::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TrafficLight::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TrafficLight::GetClassData() const { return &_class_data_; }


void TrafficLight::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TrafficLight*>(&to_msg);
  auto& from = static_cast<const TrafficLight&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:infopack.TrafficLight)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_active() != 0) {
    _this->_internal_set_active(from._internal_active());
  }
  if (from._internal_state() != 0) {
    _this->_internal_set_state(from._internal_state());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_remaining_time = from._internal_remaining_time();
  uint64_t raw_remaining_time;
  memcpy(&raw_remaining_time, &tmp_remaining_time, sizeof(tmp_remaining_time));
  if (raw_remaining_time != 0) {
    _this->_internal_set_remaining_time(from._internal_remaining_time());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_lane_length_before_intersection = from._internal_lane_length_before_intersection();
  uint64_t raw_lane_length_before_intersection;
  memcpy(&raw_lane_length_before_intersection, &tmp_lane_length_before_intersection, sizeof(tmp_lane_length_before_intersection));
  if (raw_lane_length_before_intersection != 0) {
    _this->_internal_set_lane_length_before_intersection(from._internal_lane_length_before_intersection());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TrafficLight::CopyFrom(const TrafficLight& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infopack.TrafficLight)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrafficLight::IsInitialized() const {
  return true;
}

void TrafficLight::InternalSwap(TrafficLight* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TrafficLight, _impl_.lane_length_before_intersection_)
      + sizeof(TrafficLight::_impl_.lane_length_before_intersection_)
      - PROTOBUF_FIELD_OFFSET(TrafficLight, _impl_.active_)>(
          reinterpret_cast<char*>(&_impl_.active_),
          reinterpret_cast<char*>(&other->_impl_.active_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TrafficLight::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_traffic_5flight_2eproto_getter, &descriptor_table_traffic_5flight_2eproto_once,
      file_level_metadata_traffic_5flight_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace infopack
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::infopack::TrafficLight*
Arena::CreateMaybeMessage< ::infopack::TrafficLight >(Arena* arena) {
  return Arena::CreateMessageInternal< ::infopack::TrafficLight >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
