// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: replymsg.proto

#include "replymsg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace infopack {
PROTOBUF_CONSTEXPR InstructionsProto::InstructionsProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.angle_)*/0
  , /*decltype(_impl_.sensorid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InstructionsProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstructionsProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstructionsProtoDefaultTypeInternal() {}
  union {
    InstructionsProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstructionsProtoDefaultTypeInternal _InstructionsProto_default_instance_;
PROTOBUF_CONSTEXPR InstructionsVec::InstructionsVec(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.insproto_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InstructionsVecDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstructionsVecDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstructionsVecDefaultTypeInternal() {}
  union {
    InstructionsVec _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstructionsVecDefaultTypeInternal _InstructionsVec_default_instance_;
}  // namespace infopack
static ::_pb::Metadata file_level_metadata_replymsg_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_replymsg_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_replymsg_2eproto = nullptr;

const uint32_t TableStruct_replymsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::infopack::InstructionsProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::infopack::InstructionsProto, _impl_.sensorid_),
  PROTOBUF_FIELD_OFFSET(::infopack::InstructionsProto, _impl_.angle_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::infopack::InstructionsVec, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::infopack::InstructionsVec, _impl_.insproto_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::infopack::InstructionsProto)},
  { 8, -1, -1, sizeof(::infopack::InstructionsVec)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::infopack::_InstructionsProto_default_instance_._instance,
  &::infopack::_InstructionsVec_default_instance_._instance,
};

const char descriptor_table_protodef_replymsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016replymsg.proto\022\010infopack\"4\n\021Instructio"
  "nsProto\022\020\n\010sensorid\030\001 \001(\005\022\r\n\005angle\030\002 \001(\001"
  "\"@\n\017InstructionsVec\022-\n\010insproto\030\001 \003(\0132\033."
  "infopack.InstructionsProtob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_replymsg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_replymsg_2eproto = {
    false, false, 154, descriptor_table_protodef_replymsg_2eproto,
    "replymsg.proto",
    &descriptor_table_replymsg_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_replymsg_2eproto::offsets,
    file_level_metadata_replymsg_2eproto, file_level_enum_descriptors_replymsg_2eproto,
    file_level_service_descriptors_replymsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_replymsg_2eproto_getter() {
  return &descriptor_table_replymsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_replymsg_2eproto(&descriptor_table_replymsg_2eproto);
namespace infopack {

// ===================================================================

class InstructionsProto::_Internal {
 public:
};

InstructionsProto::InstructionsProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:infopack.InstructionsProto)
}
InstructionsProto::InstructionsProto(const InstructionsProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InstructionsProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.angle_){}
    , decltype(_impl_.sensorid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.angle_, &from._impl_.angle_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.sensorid_) -
    reinterpret_cast<char*>(&_impl_.angle_)) + sizeof(_impl_.sensorid_));
  // @@protoc_insertion_point(copy_constructor:infopack.InstructionsProto)
}

inline void InstructionsProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.angle_){0}
    , decltype(_impl_.sensorid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InstructionsProto::~InstructionsProto() {
  // @@protoc_insertion_point(destructor:infopack.InstructionsProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InstructionsProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InstructionsProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InstructionsProto::Clear() {
// @@protoc_insertion_point(message_clear_start:infopack.InstructionsProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.angle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.sensorid_) -
      reinterpret_cast<char*>(&_impl_.angle_)) + sizeof(_impl_.sensorid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InstructionsProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 sensorid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.sensorid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double angle = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.angle_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InstructionsProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:infopack.InstructionsProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 sensorid = 1;
  if (this->_internal_sensorid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_sensorid(), target);
  }

  // double angle = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle = this->_internal_angle();
  uint64_t raw_angle;
  memcpy(&raw_angle, &tmp_angle, sizeof(tmp_angle));
  if (raw_angle != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_angle(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:infopack.InstructionsProto)
  return target;
}

size_t InstructionsProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:infopack.InstructionsProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double angle = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle = this->_internal_angle();
  uint64_t raw_angle;
  memcpy(&raw_angle, &tmp_angle, sizeof(tmp_angle));
  if (raw_angle != 0) {
    total_size += 1 + 8;
  }

  // int32 sensorid = 1;
  if (this->_internal_sensorid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_sensorid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InstructionsProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InstructionsProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InstructionsProto::GetClassData() const { return &_class_data_; }


void InstructionsProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InstructionsProto*>(&to_msg);
  auto& from = static_cast<const InstructionsProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:infopack.InstructionsProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_angle = from._internal_angle();
  uint64_t raw_angle;
  memcpy(&raw_angle, &tmp_angle, sizeof(tmp_angle));
  if (raw_angle != 0) {
    _this->_internal_set_angle(from._internal_angle());
  }
  if (from._internal_sensorid() != 0) {
    _this->_internal_set_sensorid(from._internal_sensorid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InstructionsProto::CopyFrom(const InstructionsProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infopack.InstructionsProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstructionsProto::IsInitialized() const {
  return true;
}

void InstructionsProto::InternalSwap(InstructionsProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InstructionsProto, _impl_.sensorid_)
      + sizeof(InstructionsProto::_impl_.sensorid_)
      - PROTOBUF_FIELD_OFFSET(InstructionsProto, _impl_.angle_)>(
          reinterpret_cast<char*>(&_impl_.angle_),
          reinterpret_cast<char*>(&other->_impl_.angle_));
}

::PROTOBUF_NAMESPACE_ID::Metadata InstructionsProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_replymsg_2eproto_getter, &descriptor_table_replymsg_2eproto_once,
      file_level_metadata_replymsg_2eproto[0]);
}

// ===================================================================

class InstructionsVec::_Internal {
 public:
};

InstructionsVec::InstructionsVec(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:infopack.InstructionsVec)
}
InstructionsVec::InstructionsVec(const InstructionsVec& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InstructionsVec* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.insproto_){from._impl_.insproto_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:infopack.InstructionsVec)
}

inline void InstructionsVec::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.insproto_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InstructionsVec::~InstructionsVec() {
  // @@protoc_insertion_point(destructor:infopack.InstructionsVec)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InstructionsVec::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.insproto_.~RepeatedPtrField();
}

void InstructionsVec::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InstructionsVec::Clear() {
// @@protoc_insertion_point(message_clear_start:infopack.InstructionsVec)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.insproto_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InstructionsVec::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .infopack.InstructionsProto insproto = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_insproto(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InstructionsVec::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:infopack.InstructionsVec)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .infopack.InstructionsProto insproto = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_insproto_size()); i < n; i++) {
    const auto& repfield = this->_internal_insproto(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:infopack.InstructionsVec)
  return target;
}

size_t InstructionsVec::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:infopack.InstructionsVec)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .infopack.InstructionsProto insproto = 1;
  total_size += 1UL * this->_internal_insproto_size();
  for (const auto& msg : this->_impl_.insproto_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InstructionsVec::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InstructionsVec::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InstructionsVec::GetClassData() const { return &_class_data_; }


void InstructionsVec::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InstructionsVec*>(&to_msg);
  auto& from = static_cast<const InstructionsVec&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:infopack.InstructionsVec)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.insproto_.MergeFrom(from._impl_.insproto_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InstructionsVec::CopyFrom(const InstructionsVec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infopack.InstructionsVec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstructionsVec::IsInitialized() const {
  return true;
}

void InstructionsVec::InternalSwap(InstructionsVec* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.insproto_.InternalSwap(&other->_impl_.insproto_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InstructionsVec::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_replymsg_2eproto_getter, &descriptor_table_replymsg_2eproto_once,
      file_level_metadata_replymsg_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace infopack
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::infopack::InstructionsProto*
Arena::CreateMaybeMessage< ::infopack::InstructionsProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::infopack::InstructionsProto >(arena);
}
template<> PROTOBUF_NOINLINE ::infopack::InstructionsVec*
Arena::CreateMaybeMessage< ::infopack::InstructionsVec >(Arena* arena) {
  return Arena::CreateMessageInternal< ::infopack::InstructionsVec >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
