// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoutingMsg.proto

#include "RoutingMsg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Planning {
PROTOBUF_CONSTEXPR RoutingPoint::RoutingPoint(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.longtitude_)*/0
  , /*decltype(_impl_.latitude_)*/0
  , /*decltype(_impl_.height_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RoutingPointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoutingPointDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoutingPointDefaultTypeInternal() {}
  union {
    RoutingPoint _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoutingPointDefaultTypeInternal _RoutingPoint_default_instance_;
PROTOBUF_CONSTEXPR RoutingPointVec::RoutingPointVec(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.routingpoints_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RoutingPointVecDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoutingPointVecDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoutingPointVecDefaultTypeInternal() {}
  union {
    RoutingPointVec _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoutingPointVecDefaultTypeInternal _RoutingPointVec_default_instance_;
}  // namespace Planning
static ::_pb::Metadata file_level_metadata_RoutingMsg_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_RoutingMsg_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_RoutingMsg_2eproto = nullptr;

const uint32_t TableStruct_RoutingMsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Planning::RoutingPoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Planning::RoutingPoint, _impl_.longtitude_),
  PROTOBUF_FIELD_OFFSET(::Planning::RoutingPoint, _impl_.latitude_),
  PROTOBUF_FIELD_OFFSET(::Planning::RoutingPoint, _impl_.height_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Planning::RoutingPointVec, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Planning::RoutingPointVec, _impl_.routingpoints_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Planning::RoutingPoint)},
  { 9, -1, -1, sizeof(::Planning::RoutingPointVec)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Planning::_RoutingPoint_default_instance_._instance,
  &::Planning::_RoutingPointVec_default_instance_._instance,
};

const char descriptor_table_protodef_RoutingMsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020RoutingMsg.proto\022\010Planning\"D\n\014RoutingP"
  "oint\022\022\n\nLongtitude\030\001 \001(\001\022\020\n\010Latitude\030\002 \001"
  "(\001\022\016\n\006Height\030\003 \001(\001\"@\n\017RoutingPointVec\022-\n"
  "\rRoutingPoints\030\001 \003(\0132\026.Planning.RoutingP"
  "ointb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_RoutingMsg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_RoutingMsg_2eproto = {
    false, false, 172, descriptor_table_protodef_RoutingMsg_2eproto,
    "RoutingMsg.proto",
    &descriptor_table_RoutingMsg_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_RoutingMsg_2eproto::offsets,
    file_level_metadata_RoutingMsg_2eproto, file_level_enum_descriptors_RoutingMsg_2eproto,
    file_level_service_descriptors_RoutingMsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_RoutingMsg_2eproto_getter() {
  return &descriptor_table_RoutingMsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_RoutingMsg_2eproto(&descriptor_table_RoutingMsg_2eproto);
namespace Planning {

// ===================================================================

class RoutingPoint::_Internal {
 public:
};

RoutingPoint::RoutingPoint(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Planning.RoutingPoint)
}
RoutingPoint::RoutingPoint(const RoutingPoint& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RoutingPoint* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.longtitude_){}
    , decltype(_impl_.latitude_){}
    , decltype(_impl_.height_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.longtitude_, &from._impl_.longtitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.height_) -
    reinterpret_cast<char*>(&_impl_.longtitude_)) + sizeof(_impl_.height_));
  // @@protoc_insertion_point(copy_constructor:Planning.RoutingPoint)
}

inline void RoutingPoint::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.longtitude_){0}
    , decltype(_impl_.latitude_){0}
    , decltype(_impl_.height_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RoutingPoint::~RoutingPoint() {
  // @@protoc_insertion_point(destructor:Planning.RoutingPoint)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RoutingPoint::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void RoutingPoint::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RoutingPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:Planning.RoutingPoint)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.longtitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.height_) -
      reinterpret_cast<char*>(&_impl_.longtitude_)) + sizeof(_impl_.height_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RoutingPoint::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double Longtitude = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.longtitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double Latitude = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double Height = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RoutingPoint::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Planning.RoutingPoint)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double Longtitude = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_longtitude = this->_internal_longtitude();
  uint64_t raw_longtitude;
  memcpy(&raw_longtitude, &tmp_longtitude, sizeof(tmp_longtitude));
  if (raw_longtitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_longtitude(), target);
  }

  // double Latitude = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_latitude(), target);
  }

  // double Height = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_height = this->_internal_height();
  uint64_t raw_height;
  memcpy(&raw_height, &tmp_height, sizeof(tmp_height));
  if (raw_height != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_height(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Planning.RoutingPoint)
  return target;
}

size_t RoutingPoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Planning.RoutingPoint)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double Longtitude = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_longtitude = this->_internal_longtitude();
  uint64_t raw_longtitude;
  memcpy(&raw_longtitude, &tmp_longtitude, sizeof(tmp_longtitude));
  if (raw_longtitude != 0) {
    total_size += 1 + 8;
  }

  // double Latitude = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    total_size += 1 + 8;
  }

  // double Height = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_height = this->_internal_height();
  uint64_t raw_height;
  memcpy(&raw_height, &tmp_height, sizeof(tmp_height));
  if (raw_height != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RoutingPoint::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RoutingPoint::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RoutingPoint::GetClassData() const { return &_class_data_; }


void RoutingPoint::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RoutingPoint*>(&to_msg);
  auto& from = static_cast<const RoutingPoint&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Planning.RoutingPoint)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_longtitude = from._internal_longtitude();
  uint64_t raw_longtitude;
  memcpy(&raw_longtitude, &tmp_longtitude, sizeof(tmp_longtitude));
  if (raw_longtitude != 0) {
    _this->_internal_set_longtitude(from._internal_longtitude());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_latitude = from._internal_latitude();
  uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    _this->_internal_set_latitude(from._internal_latitude());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_height = from._internal_height();
  uint64_t raw_height;
  memcpy(&raw_height, &tmp_height, sizeof(tmp_height));
  if (raw_height != 0) {
    _this->_internal_set_height(from._internal_height());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RoutingPoint::CopyFrom(const RoutingPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Planning.RoutingPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoutingPoint::IsInitialized() const {
  return true;
}

void RoutingPoint::InternalSwap(RoutingPoint* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RoutingPoint, _impl_.height_)
      + sizeof(RoutingPoint::_impl_.height_)
      - PROTOBUF_FIELD_OFFSET(RoutingPoint, _impl_.longtitude_)>(
          reinterpret_cast<char*>(&_impl_.longtitude_),
          reinterpret_cast<char*>(&other->_impl_.longtitude_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RoutingPoint::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RoutingMsg_2eproto_getter, &descriptor_table_RoutingMsg_2eproto_once,
      file_level_metadata_RoutingMsg_2eproto[0]);
}

// ===================================================================

class RoutingPointVec::_Internal {
 public:
};

RoutingPointVec::RoutingPointVec(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Planning.RoutingPointVec)
}
RoutingPointVec::RoutingPointVec(const RoutingPointVec& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RoutingPointVec* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.routingpoints_){from._impl_.routingpoints_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Planning.RoutingPointVec)
}

inline void RoutingPointVec::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.routingpoints_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RoutingPointVec::~RoutingPointVec() {
  // @@protoc_insertion_point(destructor:Planning.RoutingPointVec)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RoutingPointVec::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.routingpoints_.~RepeatedPtrField();
}

void RoutingPointVec::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RoutingPointVec::Clear() {
// @@protoc_insertion_point(message_clear_start:Planning.RoutingPointVec)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.routingpoints_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RoutingPointVec::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Planning.RoutingPoint RoutingPoints = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_routingpoints(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RoutingPointVec::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Planning.RoutingPointVec)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Planning.RoutingPoint RoutingPoints = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_routingpoints_size()); i < n; i++) {
    const auto& repfield = this->_internal_routingpoints(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Planning.RoutingPointVec)
  return target;
}

size_t RoutingPointVec::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Planning.RoutingPointVec)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Planning.RoutingPoint RoutingPoints = 1;
  total_size += 1UL * this->_internal_routingpoints_size();
  for (const auto& msg : this->_impl_.routingpoints_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RoutingPointVec::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RoutingPointVec::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RoutingPointVec::GetClassData() const { return &_class_data_; }


void RoutingPointVec::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RoutingPointVec*>(&to_msg);
  auto& from = static_cast<const RoutingPointVec&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Planning.RoutingPointVec)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.routingpoints_.MergeFrom(from._impl_.routingpoints_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RoutingPointVec::CopyFrom(const RoutingPointVec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Planning.RoutingPointVec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoutingPointVec::IsInitialized() const {
  return true;
}

void RoutingPointVec::InternalSwap(RoutingPointVec* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.routingpoints_.InternalSwap(&other->_impl_.routingpoints_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RoutingPointVec::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RoutingMsg_2eproto_getter, &descriptor_table_RoutingMsg_2eproto_once,
      file_level_metadata_RoutingMsg_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Planning
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Planning::RoutingPoint*
Arena::CreateMaybeMessage< ::Planning::RoutingPoint >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Planning::RoutingPoint >(arena);
}
template<> PROTOBUF_NOINLINE ::Planning::RoutingPointVec*
Arena::CreateMaybeMessage< ::Planning::RoutingPointVec >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Planning::RoutingPointVec >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
