// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_control_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_control_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_control_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_control_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_control_2eproto;
namespace controlData {
class ChassisInfo;
struct ChassisInfoDefaultTypeInternal;
extern ChassisInfoDefaultTypeInternal _ChassisInfo_default_instance_;
}  // namespace controlData
PROTOBUF_NAMESPACE_OPEN
template<> ::controlData::ChassisInfo* Arena::CreateMaybeMessage<::controlData::ChassisInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace controlData {

// ===================================================================

class ChassisInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:controlData.ChassisInfo) */ {
 public:
  inline ChassisInfo() : ChassisInfo(nullptr) {}
  ~ChassisInfo() override;
  explicit PROTOBUF_CONSTEXPR ChassisInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChassisInfo(const ChassisInfo& from);
  ChassisInfo(ChassisInfo&& from) noexcept
    : ChassisInfo() {
    *this = ::std::move(from);
  }

  inline ChassisInfo& operator=(const ChassisInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChassisInfo& operator=(ChassisInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChassisInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChassisInfo* internal_default_instance() {
    return reinterpret_cast<const ChassisInfo*>(
               &_ChassisInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChassisInfo& a, ChassisInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ChassisInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChassisInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChassisInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChassisInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChassisInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChassisInfo& from) {
    ChassisInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChassisInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "controlData.ChassisInfo";
  }
  protected:
  explicit ChassisInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpeedFieldNumber = 1,
    kSteeringAngleFieldNumber = 2,
    kModeFieldNumber = 3,
  };
  // float speed = 1;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // float steeringAngle = 2;
  void clear_steeringangle();
  float steeringangle() const;
  void set_steeringangle(float value);
  private:
  float _internal_steeringangle() const;
  void _internal_set_steeringangle(float value);
  public:

  // int32 mode = 3;
  void clear_mode();
  int32_t mode() const;
  void set_mode(int32_t value);
  private:
  int32_t _internal_mode() const;
  void _internal_set_mode(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:controlData.ChassisInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float speed_;
    float steeringangle_;
    int32_t mode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChassisInfo

// float speed = 1;
inline void ChassisInfo::clear_speed() {
  _impl_.speed_ = 0;
}
inline float ChassisInfo::_internal_speed() const {
  return _impl_.speed_;
}
inline float ChassisInfo::speed() const {
  // @@protoc_insertion_point(field_get:controlData.ChassisInfo.speed)
  return _internal_speed();
}
inline void ChassisInfo::_internal_set_speed(float value) {
  
  _impl_.speed_ = value;
}
inline void ChassisInfo::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:controlData.ChassisInfo.speed)
}

// float steeringAngle = 2;
inline void ChassisInfo::clear_steeringangle() {
  _impl_.steeringangle_ = 0;
}
inline float ChassisInfo::_internal_steeringangle() const {
  return _impl_.steeringangle_;
}
inline float ChassisInfo::steeringangle() const {
  // @@protoc_insertion_point(field_get:controlData.ChassisInfo.steeringAngle)
  return _internal_steeringangle();
}
inline void ChassisInfo::_internal_set_steeringangle(float value) {
  
  _impl_.steeringangle_ = value;
}
inline void ChassisInfo::set_steeringangle(float value) {
  _internal_set_steeringangle(value);
  // @@protoc_insertion_point(field_set:controlData.ChassisInfo.steeringAngle)
}

// int32 mode = 3;
inline void ChassisInfo::clear_mode() {
  _impl_.mode_ = 0;
}
inline int32_t ChassisInfo::_internal_mode() const {
  return _impl_.mode_;
}
inline int32_t ChassisInfo::mode() const {
  // @@protoc_insertion_point(field_get:controlData.ChassisInfo.mode)
  return _internal_mode();
}
inline void ChassisInfo::_internal_set_mode(int32_t value) {
  
  _impl_.mode_ = value;
}
inline void ChassisInfo::set_mode(int32_t value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:controlData.ChassisInfo.mode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace controlData

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_control_2eproto
